samples:
    0: "3448_L003"
    1: "3449_L004"
    2: "3454_L003"
    3: "3465_L003"
    4: "3466_L004"
    5: "3481_L004"
    6: "3502_L003"
    7: "3539_L003"
    8: "3541_L003"
    9: "3567_L003"
    10: "3592_L004"
    11: "3641_L004"
    12: "3653_L003"
    13: "3659_L003"
    14: "3685_L004"
    15: "3689_L004"
    16: "369_L004"
    17: "3709_L004"
    18: "3771_L003"
    19: "3790_L003"
    20: "3791_L003"
    21: "3832_L004"
    22: "3850_L004"
    23: "3851_L004"
    24: "3873_L003"
    25: "388_L004"
    26: "3915_L003"
    27: "3920_L003"
    28: "3921_L003"
    29: "3952_L004"
    30: "396_L004"
    31: "3973_L004"
    32: "3974_L004"
    33: "39_L004"
    34: "4004_L003"
    35: "4008_L003"
    36: "4009_L004"
    37: "4016_L004"
    38: "4043_L003"
    39: "4066_L003"
    40: "4084_L004"
    41: "4152_L004"
    42: "4163_L004"
    43: "4171_L004"
    44: "4175_L003"
    45: "4210_L003"
    46: "4217_L004"
    47: "4255_L004"
    48: "4257_L003"
    49: "4266_L003"
