samples:
    0: "10021_L003"
    1: "10036_L003"
    2: "10101_L003"
    3: "10115_L003"
    4: "10135_L003"
    5: "10141_L004"
    6: "10144_L003"
    7: "10157_L004"
    8: "10160_L004"
    9: "10189_L004"
    10: "10201_L004"
    11: "10204_L004"
    12: "10218_L003"
    13: "10221_L003"
    14: "10228_L004"
    15: "10234_L003"
    16: "10332_L004"
    17: "1036_L004"
    18: "10381_L004"
    19: "10407_L004"
    20: "10420_L004"
    21: "10423_L004"
    22: "10424_L003"
    23: "10434_L003"
    24: "1043_L003"
    25: "10445_L004"
    26: "10473_L003"
    27: "10503_L003"
    28: "10507_L003"
    29: "10543_L003"
    30: "10544_L003"
    31: "1054_L004"
    32: "10610_L003"
    33: "10634_L004"
    34: "10646_L004"
    35: "10659_L004"
    36: "10689_L004"
    37: "10693_L004"
    38: "10709_L004"
    39: "10728_L003"
    40: "10746_L004"
    41: "10755_L004"
    42: "10758_L004"
    43: "10769_L004"
    44: "10812_L004"
    45: "10818_L004"
    46: "1081_L003"
    47: "10896_L003"
    48: "10898_L004"
    49: "10911_L004"
