samples:
    0: "7955_L004"
    1: "796_L003"
    2: "7976_L003"
    3: "7984_L003"
    4: "7993_L004"
    5: "8002_L003"
    6: "8007_L004"
    7: "8011_L003"
    8: "804_L004"
    9: "8062_L003"
    10: "8067_L003"
    11: "8089_L004"
    12: "8097_L003"
    13: "8116_L003"
    14: "8120_L004"
    15: "8131_L003"
    16: "8144_L003"
    17: "8147_L003"
    18: "8152_L004"
    19: "815_L004"
    20: "8164_L004"
    21: "8194_L004"
    22: "8231_L003"
    23: "825_L003"
    24: "8261_L004"
    25: "8267_L003"
    26: "8304_L004"
    27: "8336_L003"
    28: "8338_L003"
    29: "8352_L003"
    30: "8355_L003"
    31: "835_L004"
    32: "8361_L003"
    33: "8363_L003"
    34: "839_L004"
    35: "83_L004"
    36: "8404_L004"
    37: "8407_L003"
    38: "8415_L003"
    39: "842_L004"
    40: "8433_L004"
    41: "8452_L003"
    42: "8483_L003"
    43: "8508_L004"
    44: "850_L003"
    45: "8511_L004"
    46: "851_L004"
    47: "8520_L004"
    48: "8532_L003"
    49: "8540_L004"
