samples:
    0: "19319_L003"
    1: "19436_L004"
    2: "1943_L004"
    3: "19451_L004"
    4: "19476_L004"
    5: "194_L003"
    6: "19500_L003"
    7: "19534_L004"
    8: "1954_L003"
    9: "19566_L003"
    10: "19579_L003"
    11: "19599_L003"
    12: "19602_L003"
    13: "1960_L004"
    14: "19626_L004"
    15: "19639_L004"
    16: "19655_L003"
    17: "19676_L003"
    18: "1975_L004"
    19: "19774_L003"
    20: "19779_L003"
    21: "19855_L004"
    22: "19929_L004"
    23: "19933_L004"
    24: "19940_L004"
    25: "1994_L003"
    26: "19966_L004"
    27: "19996_L004"
    28: "20017_L003"
    29: "2001_L003"
    30: "20025_L003"
    31: "20030_L004"
    32: "20040_L003"
    33: "2010-11208_L003"
    34: "2010-1204_L003"
    35: "2010-16950_L003"
    36: "2010-18935_L003"
    37: "2010-3061_L003"
    38: "2010-3453_L003"
    39: "20108_L003"
    40: "2011-14541_L003"
    41: "2011-2860_L003"
    42: "2011-615_L003"
    43: "2012-10437_L003"
    44: "2012-14541_L003"
    45: "2012-16950_L003"
    46: "2012-3205_L003"
    47: "2012-4920_L003"
    48: "2012-6812_L003"
    49: "2012-7725_L003"
