samples:
    0: "20457_L004"
    1: "20518_L003"
    2: "20608_L004"
    3: "20612_L003"
    4: "20638_L004"
    5: "20669_L004"
    6: "2072_L004"
    7: "2073_L004"
    8: "2081_L004"
    9: "20826_L003"
    10: "20865_L004"
    11: "2088_L004"
    12: "21001_L003"
    13: "21006_L004"
    14: "21029_L003"
    15: "21031_L003"
    16: "21066_L004"
    17: "21095_L004"
    18: "210_L004"
    19: "21126_L004"
    20: "21152_L004"
    21: "21199_L004"
    22: "211_L003"
    23: "21205_L004"
    24: "21284_L004"
    25: "21311_L004"
    26: "21329_L004"
    27: "21332_L004"
    28: "21361_L004"
    29: "21365_L004"
    30: "2137_L004"
    31: "21447_L004"
    32: "21472_L003"
    33: "2155_L004"
    34: "21578_L004"
    35: "21602_L004"
    36: "21616_L004"
    37: "2161_L004"
    38: "2162_L004"
    39: "2163_L004"
    40: "21648_L004"
    41: "21667_L004"
    42: "21720_L004"
    43: "21771_L004"
    44: "21782_L004"
    45: "21797_L004"
    46: "21804_L004"
    47: "21884_L003"
    48: "2189_L003"
    49: "21919_L004"
