samples:
    0: "1628_L004"
    1: "16379_L003"
    2: "16391_L003"
    3: "16421_L004"
    4: "16482_L004"
    5: "16488_L004"
    6: "16576_L004"
    7: "16582_L003"
    8: "16625_L004"
    9: "16711_L003"
    10: "16723_L004"
    11: "16751_L003"
    12: "16757_L004"
    13: "16768_L004"
    14: "1676_L003"
    15: "16771_L003"
    16: "16787_L003"
    17: "16817_L004"
    18: "1681_L003"
    19: "16830_L003"
    20: "16838_L004"
    21: "1685_L003"
    22: "16889_L003"
    23: "16905_L003"
    24: "16921_L004"
    25: "1692_L003"
    26: "16935_L004"
    27: "16969_L003"
    28: "16977_L003"
    29: "16978_L003"
    30: "16999_L004"
    31: "17015_L004"
    32: "1702_L003"
    33: "1703_L003"
    34: "1706_L003"
    35: "17079_L003"
    36: "17120_L003"
    37: "17125_L003"
    38: "17170_L003"
    39: "1719_L004"
    40: "17212_L003"
    41: "17262_L003"
    42: "17272_L003"
    43: "17326_L003"
    44: "17342_L004"
    45: "17386_L003"
    46: "17396_L003"
    47: "1749_L003"
    48: "17569_L003"
    49: "17632_L003"
