samples:
    0: "6471_L004"
    1: "6487_L003"
    2: "6493_L003"
    3: "6530_L003"
    4: "6555_L004"
    5: "6557_L003"
    6: "6567_L004"
    7: "6581_L003"
    8: "6600_L004"
    9: "6608_L003"
    10: "6615_L003"
    11: "6616_L004"
    12: "6622_L003"
    13: "6639_L004"
    14: "6664_L004"
    15: "6708_L003"
    16: "6743_L003"
    17: "6760_L004"
    18: "6798_L003"
    19: "6808_L004"
    20: "680_L003"
    21: "6810_L003"
    22: "6813_L003"
    23: "6834_L003"
    24: "6861_L003"
    25: "686_L004"
    26: "6879_L003"
    27: "6895_L003"
    28: "6900_L004"
    29: "6913_L004"
    30: "6914_L004"
    31: "6915_L003"
    32: "6939_L004"
    33: "694_L003"
    34: "6952_L004"
    35: "6967_L003"
    36: "7013_L003"
    37: "7021_L003"
    38: "7051_L004"
    39: "7067_L003"
    40: "7084_L003"
    41: "7089_L004"
    42: "710_L003"
    43: "7112_L004"
    44: "7122_L003"
    45: "7132_L003"
    46: "7135_L004"
    47: "7148_L004"
    48: "7161_L003"
    49: "7168_L004"
