samples:
    0: "TB_TG1466829_S54_L001"
    1: "TB_TG1467103_S159_L001"
    2: "TB_TG1466965_S109_L001"
    3: "TB_TG1466751_S24_L001"
    4: "TB_TG1466897_S81_L001"
    5: "TB_TG1467117_S164_L001"
    6: "TB_TG1466903_S83_L001"
    7: "TB_TG1466769_S32_L001"
    8: "TB_TG1466993_S122_L001"
    9: "TB_TG1467085_S155_L001"
    10: "TB_TG1466787_S38_L001"
    11: "TB_TG1466689_S3_L001"
    12: "TB_TG1466705_S134_L001"
    13: "TB_TG1466941_S100_L001"
    14: "TB_TG1466959_S107_L001"
    15: "TB_TG1466977_S115_L001"
    16: "TB_TG1466203_S76_L001"
    17: "TB_TG1467213_S202_L001"
    18: "TB_TG1466901_S82_L001"
    19: "TB_TG1466781_S36_L001"
    20: "TB_TG1466835_S57_L001"
    21: "TB_TG1467131_S169_L001"
    22: "TB_TG1466741_S20_L001"
    23: "TB_TG1466885_S77_L001"
    24: "TB_TG1467017_S133_L001"
    25: "TB_TG1467053_S145_L001"
    26: "TB_TG1467141_S173_L001"
    27: "TB_TG1466821_S51_L001"
    28: "TB_TG1467147_S176_L001"
    29: "TB_TG1467043_S142_L001"
    30: "TB_TG1467187_S194_L001"
    31: "TB_TG1466809_S47_L001"
    32: "TB_TG1466789_S39_L001"
    33: "TB_TG1466985_S118_L001"
    34: "TB_TG1466693_S5_L001"
    35: "TB_TG1466873_S72_L001"
    36: "TB_TG1466929_S95_L001"
    37: "TB_TG1466733_S16_L001"
    38: "TB_TG1466857_S66_L001"
    39: "TB_TG1467027_S137_L001"
    40: "TB_TG1467049_S144_L001"
    41: "TB_TG1467091_S157_L001"
    42: "TB_TG1466827_S53_L001"
    43: "TB_TG1467125_S13_L001"
    44: "TB_TG1466757_S141_L001"
    45: "TB_TG1466833_S56_L001"
    46: "TB_TG1466691_S4_L001"
    47: "TB_TG1466983_S117_L001"
    48: "TB_TG1466991_S121_L001"
    49: "TB_TG1467243_S217_L001"
