samples:
    0: "TB_TG1467055_S146_L001"
    1: "TB_TG1467127_S167_L001"
    2: "TB_TG1467145_S175_L001"
    3: "TB_TG1466783_S144_L001"
    4: "TB_TG1466699_S7_L001"
    5: "TB_TG1466825_S146_L001"
    6: "TB_TG1466975_S114_L001"
    7: "TB_TG1466971_S112_L001"
    8: "TB_TG1466845_S62_L001"
    9: "TB_TG1467119_S165_L001"
    10: "TB_TG1466795_S42_L001"
    11: "TB_TG1467225_S208_L001"
    12: "TB_TG1467037_S141_L001"
    13: "TB_TG1467231_S211_L001"
    14: "TB_TG1467045_S143_L001"
    15: "TB_TG1466679_S128_L001"
    16: "TB_TG1466969_S111_L001"
    17: "TB_TG1466863_S69_L001"
    18: "TB_TG1466715_S11_L001"
    19: "TB_TG1467079_S152_L001"
    20: "TB_TG1467171_S187_L001"
    21: "TB_TG1466779_S143_L001"
    22: "TB_TG1466735_S17_L001"
    23: "TB_TG1467207_S200_L001"
    24: "TB_TG1466879_S132_L001"
    25: "TB_TG1466819_S50_L001"
    26: "TB_TG1467007_S129_L001"
    27: "TB_TG1466987_S119_L001"
    28: "TB_TG1467005_S128_L001"
    29: "TB_TG1466937_S98_L001"
    30: "TB_TG1466967_S110_L001"
    31: "TB_TG1467083_S154_L001"
    32: "TB_TG1467113_S162_L001"
    33: "TB_TG1466749_S23_L001"
    34: "TB_TG1466607_S123_L001"
    35: "TB_TG1467057_S147_L001"
    36: "TB_TG1466681_S129_L001"
    37: "TB_TG1466951_S104_L001"
    38: "TB_TG1467235_S213_L001"
    39: "TB_TG1467015_S132_L001"
    40: "TB_TG1466931_S96_L001"
    41: "TB_TG1467215_S203_L001"
    42: "TB_TG1466697_S132_L001"
    43: "TB_TG1466771_S33_L001"
    44: "TB_TG1466837_S58_L001"
    45: "TB_TG1466755_S26_L001"
    46: "TB_TG1466939_S99_L001"
    47: "TB_TG1467157_S181_L001"
    48: "TB_TG1467175_S188_L001"
    49: "TB_TG1467169_S186_L001"
