samples:
    0: "TB_TG1466773_S34_L001"
    1: "TB_TG1467019_S134_L001"
    2: "TB_TG1466275_S88_L001"
    3: "TB_TG1466687_S2_L001"
    4: "TB_TG1467041_S161_L001"
    5: "TB_TG1466865_S148_L001"
    6: "TB_TG1466869_S70_L001"
    7: "TB_TG1467151_S178_L001"
    8: "TB_TG1466159_S69_L001"
    9: "TB_TG1466871_S71_L001"
    10: "TB_TG1467067_S149_L001"
    11: "TB_TG1467149_S177_L001"
    12: "TB_TG1467165_S184_L001"
    13: "TB_TG1467229_S210_L001"
    14: "TB_TG1466813_S49_L001"
    15: "TB_TG1467025_S136_L001"
    16: "TB_TG1466921_S91_L001"
    17: "TB_TG1466725_S13_L001"
    18: "TB_TG1466915_S88_L001"
    19: "TB_TG1467003_S127_L001"
    20: "TB_TG1467237_S214_L001"
    21: "TB_TG1466989_S120_L001"
    22: "TB_TG1466907_S85_L001"
