samples:
    0: "TB_TG1466963_S108_L001"
    1: "TB_TG1467159_S182_L001"
    2: "TB_TG1467161_S183_L001"
    3: "TB_TG1467219_S205_L001"
    4: "TB_TG1466973_S113_L001"
    5: "TB_TG1466785_S37_L001"
    6: "TB_TG1466935_S97_L001"
    7: "TB_TG1466801_S43_L001"
    8: "TB_TG1466729_S14_L001"
    9: "TB_TG1466883_S76_L001"
    10: "TB_TG1467109_S160_L001"
    11: "TB_TG1466919_S90_L001"
    12: "TB_TG1467061_S148_L001"
    13: "TB_TG1466701_S8_L001"
    14: "TB_TG1466947_S102_L001"
    15: "TB_TG1466721_S138_L001"
    16: "TB_TG1466925_S93_L001"
    17: "TB_TG1466945_S101_L001"
    18: "TB_TG1466995_S123_L001"
    19: "TB_TG1466745_S21_L001"
    20: "TB_TG1466237_S83_L001"
    21: "TB_TG1466917_S89_L001"
    22: "TB_TG1467205_S199_L001"
    23: "TB_TG1467031_S139_L001"
    24: "TB_TG1466765_S30_L001"
    25: "TB_TG1466923_S92_L001"
    26: "TB_TG1466891_S79_L001"
    27: "TB_TG1466953_S105_L001"
    28: "TB_TG1467143_S174_L001"
    29: "TB_TG1467217_S204_L001"
    30: "TB_TG1467075_S150_L001"
    31: "TB_TG1466703_S133_L001"
    32: "TB_TG1466867_S101_L001"
    33: "TB_TG1467095_S10_L001"
    34: "TB_TG1466775_S35_L001"
    35: "TB_TG1466807_S46_L001"
    36: "TB_TG1467013_S131_L001"
    37: "TB_TG1466761_S28_L001"
    38: "TB_TG1466849_S64_L001"
    39: "TB_TG1466731_S15_L001"
    40: "TB_TG1466839_S59_L001"
    41: "TB_TG1467139_S172_L001"
    42: "TB_TG1467155_S180_L001"
    43: "TB_TG1467177_S189_L001"
    44: "TB_TG1466767_S31_L001"
    45: "TB_TG1467121_S166_L001"
    46: "TB_TG1467197_S197_L001"
    47: "TB_TG1467201_S198_L001"
    48: "TB_TG1466709_S9_L001"
    49: "TB_TG1466843_S61_L001"
