samples:
    0: "4267_L003"
    1: "4277_L004"
    2: "4281_L003"
    3: "4289_L004"
    4: "4297_L004"
    5: "4303_L004"
    6: "4308_L004"
    7: "4341_L003"
    8: "434_L003"
    9: "4362_L004"
    10: "4366_L003"
    11: "4369_L004"
    12: "4394_L003"
    13: "4397_L004"
    14: "4413_L003"
    15: "4424_L004"
    16: "4428_L004"
    17: "4429_L004"
    18: "4458_L004"
    19: "4488_L004"
    20: "4489_L004"
    21: "4492_L003"
    22: "4510_L003"
    23: "4522_L004"
    24: "4535_L004"
    25: "4538_L004"
    26: "4540_L003"
    27: "4544_L004"
    28: "4547_L003"
    29: "4549_L003"
    30: "454_L004"
    31: "4554_L003"
    32: "456_L004"
    33: "4582_L004"
    34: "4593_L004"
    35: "4601_L003"
    36: "4614_L003"
    37: "4627_L004"
    38: "4640_L003"
    39: "4660_L004"
    40: "4673_L004"
    41: "4679_L004"
    42: "46_L004"
    43: "4704_L004"
    44: "4706_L004"
    45: "4728_L004"
    46: "4736_L003"
    47: "4744_L003"
    48: "4747_L003"
    49: "4774_L003"
