samples:
    0: "2012-8190_L003"
    1: "2012-9210_L003"
    2: "2012-9263_L003"
    3: "2013-10439_L003"
    4: "2013-2860_L003"
    5: "2013-3061_L003"
    6: "2013-3141_L003"
    7: "2013-3274_L003"
    8: "2013-336_L003"
    9: "2013-3693_L003"
    10: "2013-3788_L003"
    11: "2013-4920_L003"
    12: "2013-5189_L003"
    13: "2013-5223_L004"
    14: "2013-6812_L003"
    15: "2013-7398_L003"
    16: "2013-9026_L003"
    17: "2013-9263_L003"
    18: "20136_L004"
    19: "2014-11208_L003"
    20: "2014-18935_L003"
    21: "2014-3205_L003"
    22: "2014-3453_L003"
    23: "2014-3693_L003"
    24: "2014-4922_L003"
    25: "20148_L003"
    26: "2015-1204_L004"
    27: "2015-1266_L004"
    28: "2015-3141_L004"
    29: "2015-3274_L004"
    30: "2015-336_L004"
    31: "2015-8190_L004"
    32: "2016-10437_L004"
    33: "2016-10439_L004"
    34: "2016-1266_L004"
    35: "2016-3788_L004"
    36: "2016-4922_L004"
    37: "2016-5189_L004"
    38: "2016-5223_L004"
    39: "2016-615_L004"
    40: "2016-7398_L004"
    41: "2016-7725_L004"
    42: "2016-9026_L004"
    43: "2016-9210_L004"
    44: "2021_L003"
    45: "20248_L003"
    46: "20296_L003"
    47: "202_L003"
    48: "2034_L003"
    49: "2044_L003"
