samples:
    0: "4778_L004"
    1: "4792_L004"
    2: "4805_L003"
    3: "4809_L003"
    4: "481_L003"
    5: "4828_L004"
    6: "4830_L004"
    7: "4835_L003"
    8: "484_L003"
    9: "4861_L004"
    10: "4874_L004"
    11: "4891_L003"
    12: "4893_L004"
    13: "4914_L003"
    14: "4918_L004"
    15: "4938_L004"
    16: "4940_L003"
    17: "4948_L003"
    18: "4954_L003"
    19: "4968_L004"
    20: "4972_L003"
    21: "4980_L003"
    22: "4982_L003"
    23: "49_L004"
    24: "5014_L004"
    25: "5026_L004"
    26: "5037_L004"
    27: "5067_L003"
    28: "5085_L004"
    29: "5086_L004"
    30: "5098_L004"
    31: "5108_L003"
    32: "512_L003"
    33: "5137_L004"
    34: "5143_L003"
    35: "5187_L004"
    36: "5199_L003"
    37: "5202_L004"
    38: "5213_L004"
    39: "5216_L003"
    40: "5222_L003"
    41: "5224_L004"
    42: "5239_L004"
    43: "5240_L004"
    44: "5262_L003"
    45: "5268_L003"
    46: "5295_L003"
    47: "5334_L004"
    48: "5338_L003"
    49: "5339_L003"
