samples:
    0: "10950_L004"
    1: "10955_L004"
    2: "10969_L003"
    3: "10973_L003"
    4: "10989_L004"
    5: "10998_L004"
    6: "11017_L003"
    7: "11061_L004"
    8: "11068_L003"
    9: "11069_L004"
    10: "11097_L003"
    11: "11099_L004"
    12: "11115_L004"
    13: "11120_L004"
    14: "11144_L004"
    15: "11148_L003"
    16: "11257_L003"
    17: "11267_L004"
    18: "11270_L003"
    19: "11271_L004"
    20: "1136_L004"
    21: "11374_L004"
    22: "11447_L004"
    23: "1144_L004"
    24: "11463_L004"
    25: "11472_L003"
    26: "1148_L003"
    27: "11528_L004"
    28: "11586_L004"
    29: "11588_L003"
    30: "11604_L003"
    31: "11615_L003"
    32: "11630_L004"
    33: "11671_L004"
    34: "1176_L003"
    35: "11783_L003"
    36: "11821_L004"
    37: "11835_L004"
    38: "1184_L003"
    39: "11851_L003"
    40: "11856_L003"
    41: "11935_L003"
    42: "11954_L003"
    43: "11979_L004"
    44: "1198_L003"
    45: "1205_L004"
    46: "12202_L003"
    47: "12213_L004"
    48: "12233_L003"
    49: "12257_L004"
