samples:
    0: "12273_L003"
    1: "12301_L003"
    2: "12318_L003"
    3: "1233_L003"
    4: "12348_L004"
    5: "12389_L003"
    6: "12403_L003"
    7: "12429_L003"
    8: "12430_L003"
    9: "12440_L003"
    10: "12486_L004"
    11: "12507_L003"
    12: "12515_L003"
    13: "1254_L003"
    14: "12550_L003"
    15: "12580_L003"
    16: "12625_L003"
    17: "12637_L004"
    18: "12640_L003"
    19: "12682_L003"
    20: "12684_L003"
    21: "1268_L003"
    22: "12718_L004"
    23: "12800_L004"
    24: "12804_L003"
    25: "12845_L003"
    26: "12873_L003"
    27: "1288_L003"
    28: "12941_L003"
    29: "1296_L004"
    30: "12998_L004"
    31: "13010_L003"
    32: "1303_L004"
    33: "13103_L003"
    34: "13106_L003"
    35: "13109_L003"
    36: "13115_L003"
    37: "13149_L003"
    38: "13186_L003"
    39: "13188_L004"
    40: "1327_L003"
    41: "1327_rerun_S203_L001"
    42: "13283_L004"
    43: "1328_L004"
    44: "13294_L003"
    45: "13305_L004"
    46: "1337_L004"
    47: "13402_L004"
    48: "13413_L004"
    49: "13439_L003"
