samples:
    0: "17699_L003"
    1: "17723_L003"
    2: "17730_L003"
    3: "17742_L004"
    4: "17778_L003"
    5: "1779_L003"
    6: "17843_L003"
    7: "1789_L003"
    8: "17930_L004"
    9: "1793_L004"
    10: "17985_L003"
    11: "17986_L003"
    12: "18027_L003"
    13: "18041_L004"
    14: "18048_L003"
    15: "1804_L004"
    16: "18059_L004"
    17: "18105_L003"
    18: "1813_L003"
    19: "1814_L003"
    20: "18156_L003"
    21: "1820_L003"
    22: "18225_L004"
    23: "1831_L003"
    24: "18353_L003"
    25: "18457_L004"
    26: "18546_L004"
    27: "18571_L003"
    28: "1857_L003"
    29: "1859_L003"
    30: "18618_L003"
    31: "18689_L003"
    32: "18771_L004"
    33: "18782_L003"
    34: "1888_L004"
    35: "18911_L003"
    36: "18934_L004"
    37: "18967_L004"
    38: "18969_L003"
    39: "1897_L003"
    40: "1902_L004"
    41: "19065_L004"
    42: "1906_L003"
    43: "19076_L004"
    44: "1907_L003"
    45: "1910_L004"
    46: "19228_L003"
    47: "1925_L004"
    48: "19267_L003"
    49: "1926_L004"
