samples:
    0: "TB_TG1466441_S123_L001"
    1: "TB-TG1466093_L008"
    2: "TB-TG1465485_L008"
    3: "TB-TG1467291_L008"
    4: "TB-TG1461687_L008"
    5: "TB-TG1465465_L008"
    6: "TB-TG1465823_L008"
    7: "TB-TG1466033_L008"
    8: "TB_TG1466465_S135_L001"
    9: "TB-TG1466003_L008"
    10: "TB-TG1465075_L008"
    11: "TB-TG1467267_L008"
    12: "TB-TG1465979_L008"
    13: "TB-TG1461455_L008"
    14: "TB-TG1465505_L008"
    15: "TB_TG1466307_S67_L001"
    16: "TB-TG1467401_L008"
    17: "TB-TG1461477_L008"
    18: "TB_TG1466591_S182_L001"
    19: "TB-TG1461691_L008"
    20: "TB-TG1466007_L008"
    21: "TB_TG1466657_S210_L001"
    22: "TB-TG1465877_L008"
    23: "TB-TG1461495_L008"
    24: "TB_TG1466659_S211_L001"
    25: "TB-TG1467515_L008"
    26: "TB-TG1465989_L008"
    27: "TB-TG1465585_L008"
    28: "TB-TG1461743_L008"
    29: "TB-TG1467279_L008"
    30: "TB-TG1467503_L008"
    31: "TB-TG1467495_L008"
    32: "TB_TG1466463_S134_L001"
    33: "TB-TG1461559_L008"
    34: "TB-TG1465199_L008"
    35: "TB_TG1466213_S36_L001"
    36: "TB-TG1465597_L008"
    37: "TB-TG1465159_L008"
    38: "TB-TG1465983_L008"
    39: "TB-TG1466073_L008"
    40: "TB_TG1466511_S151_L001"
    41: "TB-TG1465055_L008"
    42: "TB-TG1465825_L008"
    43: "TB-TG1466071_L008"
    44: "TB-TG1465579_L008"
    45: "TB_TG1466539_S164_L001"
    46: "TB-TG1467299_L008"
    47: "TB-TG1461637_L008"
    48: "TB_TG1466195_S31_L001"
    49: "TB-TG1465867_L008"
