samples:
    0: "TB-TG1466055_L008"
    1: "TB-TG1465275_L008"
    2: "TB-TG1465281_L008"
    3: "TB-TG1466067_L008"
    4: "TB-TG1465065_L008"
    5: "TB_TG1466163_S19_L001"
    6: "TB_TG1466457_S131_L001"
    7: "TB-TG1465813_L008"
    8: "TB-TG1467505_L008"
    9: "TB-TG1465117_L008"
    10: "TB-TG1465771_L008"
    11: "TB-TG1465995_L008"
    12: "TB_TG1466405_S106_L001"
    13: "TB-TG1465987_L008"
    14: "TB-TG1467255_L008"
    15: "TB_TG1466419_S113_L001"
    16: "TB-TG1461665_L008"
    17: "TB-TG1465235_L008"
    18: "TB-TG1465903_L008"
    19: "TB_TG1466595_S184_L001"
    20: "TB-TG1467477_L008"
    21: "TB-TG1465031_L008"
    22: "TB-TG1465913_L008"
    23: "TB-TG1467393_L008"
    24: "TB-TG1461533_L008"
    25: "TB-TG1465105_L008"
    26: "TB-TG1461519_L008"
    27: "TB-TG1467443_L008"
    28: "TB_TG1466537_S163_L001"
    29: "TB-TG1465195_L008"
    30: "TB_TG1466333_S80_L001"
    31: "TB_TG1466165_S20_L001"
    32: "TB-TG1465967_L008"
    33: "TB_TG1466567_S176_L001"
    34: "TB-TG1467271_L008"
    35: "TB-TG1467447_L008"
    36: "TB_TG1466111_S3_L001"
    37: "TB-TG1465237_L008"
    38: "TB-TG1464989_L008"
    39: "TB-TG1465783_L008"
    40: "TB_TG1466331_S79_L001"
    41: "TB-TG1465479_L008"
    42: "TB-TG1467521_L008"
    43: "TB-TG1464987_L008"
    44: "TB-TG1461671_L008"
    45: "TB-TG1465083_L008"
    46: "TB-TG1465037_L008"
    47: "TB-TG1465951_L008"
    48: "TB_TG1466329_S78_L001"
    49: "TB-TG1465819_L008"
