samples:
    0: "TB_TG1466191_S29_L001"
    1: "TB-TG1467429_L008"
    2: "TB-TG1461555_L008"
    3: "TB-TG1465937_L008"
    4: "TB_TG1466189_S28_L001"
    5: "TB-TG1465227_L008"
    6: "TB_TG1466229_S42_L001"
    7: "TB-TG1461725_L008"
    8: "TB-TG1461505_L008"
    9: "TB-TG1465149_L008"
    10: "TB-TG1465581_L008"
    11: "TB-TG1464983_L008"
    12: "TB-TG1467289_L008"
    13: "TB-TG1465261_L008"
    14: "TB-TG1465567_L008"
    15: "TB-TG1465023_L008"
    16: "TB-TG1465959_L008"
    17: "TB-TG1467387_L008"
    18: "TB-TG1461465_L008"
    19: "TB-TG1461537_L008"
    20: "TB-TG1465043_L008"
    21: "TB-TG1467397_L008"
    22: "TB-TG1465233_L008"
    23: "TB_TG1466295_S62_L001"
    24: "TB-TG1465533_L008"
    25: "TB-TG1467361_L008"
    26: "TB-TG1465999_L008"
    27: "TB_TG1466485_S142_L001"
    28: "TB-TG1467351_L008"
    29: "TB-TG1465045_L008"
    30: "TB-TG1465461_L008"
    31: "TB-TG1467383_L008"
    32: "TB_TG1466559_S172_L001"
    33: "TB-TG1465119_L008"
    34: "TB-TG1465001_L008"
    35: "TB_TG1466609_S189_L001"
    36: "TB-TG1461593_L008"
    37: "TB-TG1461471_L008"
    38: "TB-TG1461709_L008"
    39: "TB-TG1467481_L008"
    40: "TB-TG1461575_L008"
    41: "TB-TG1465223_L008"
    42: "TB_TG1466249_S47_L001"
    43: "TB_TG1466563_S174_L001"
    44: "TB_TG1466169_S22_L001"
    45: "TB_TG1466283_S61_L001"
    46: "TB-TG1467325_L008"
    47: "TB_TG1466255_S50_L001"
    48: "TB-TG1467349_L008"
    49: "TB-TG1465941_L008"
