samples:
    0: "TB-TG1466019_L008"
    1: "TB-TG1465047_L008"
    2: "TB-TG1461707_L008"
    3: "TB_TG1466361_S88_L001"
    4: "TB-TG1467379_L008"
    5: "TB-TG1461515_L008"
    6: "TB-TG1461713_L008"
    7: "TB-TG1467431_L008"
    8: "TB-TG1465285_L008"
    9: "TB-TG1465551_L008"
    10: "TB-TG1465947_L008"
    11: "TB-TG1467399_L008"
    12: "TB-TG1465063_L008"
    13: "TB-TG1461585_L008"
    14: "TB-TG1461669_L008"
    15: "TB-TG1465555_L008"
    16: "TB_TG1466425_S115_L001"
    17: "TB-TG1465905_L008"
    18: "TB-TG1461645_L008"
    19: "TB-TG1467491_L008"
    20: "TB-TG1461525_L008"
    21: "TB-TG1465157_L008"
    22: "TB-TG1465147_L008"
    23: "TB-TG1467339_L008"
    24: "TB-TG1461561_L008"
    25: "TB_TG1466379_S95_L001"
    26: "TB-TG1465209_L008"
    27: "TB_TG1466271_S56_L001"
    28: "TB-TG1465509_L008"
    29: "TB-TG1467285_L008"
    30: "TB_TG1466239_S44_L001"
    31: "TB_tg1461623_S13_L001"
    32: "TB-TG1465245_L008"
    33: "TB-TG1467347_L008"
    34: "TB_TG1466517_S154_L001"
    35: "TB-TG1466097_L008"
    36: "TB-TG1465859_L008"
    37: "TB_TG1466515_S153_L001"
    38: "TB-TG1465921_L008"
    39: "TB_TG1466483_S141_L001"
    40: "TB-TG1461761_L008"
    41: "TB-TG1465881_L008"
    42: "TB-TG1465907_L008"
    43: "TB-TG1461739_L008"
    44: "TB-TG1465971_L008"
    45: "TB-TG1465253_L008"
    46: "TB-TG1465833_L008"
    47: "TB_TG1466127_S9_L001"
    48: "TB_TG1466611_S190_L001"
    49: "TB-TG1461557_L008"
