samples:
    0: "TB-TG1467513_L008"
    1: "TB-TG1467321_L008"
    2: "TB-TG1465183_L008"
    3: "TB-TG1467525_L008"
    4: "TB-TG1467409_L008"
    5: "TB-TG1461517_L008"
    6: "TB-TG1461641_L008"
    7: "TB-TG1465447_L008"
    8: "TB_TG1466115_S4_L001"
    9: "TB-TG1465997_L008"
    10: "TB_TG1466453_S129_L001"
    11: "TB-TG1467385_L008"
    12: "TB_TG1466507_S149_L001"
    13: "TB-TG1465121_L008"
    14: "TB-TG1467323_L008"
    15: "TB-TG1465271_L008"
    16: "TB-TG1465027_L008"
    17: "TB-TG1465779_L008"
    18: "TB-TG1464971_L008"
    19: "TB-TG1467403_L008"
    20: "TB_TG1466375_S93_L001"
    21: "TB-TG1467511_L008"
    22: "TB-TG1461521_L008"
    23: "TB-TG1465033_L008"
    24: "TB_tg1461631_S16_L001"
    25: "TB-TG1467305_L008"
    26: "TB-TG1467457_L008"
    27: "TB-TG1465489_L008"
    28: "TB-TG1466091_L008"
    29: "TB-TG1465263_L008"
    30: "TB-TG1465229_L008"
    31: "TB-TG1465919_L008"
    32: "TB-TG1461543_L008"
    33: "TB-TG1461729_L008"
    34: "TB_TG1466151_S17_L001"
    35: "TB_TG1466397_S102_L001"
    36: "TB-TG1465923_L008"
    37: "TB_TG1466437_S121_L001"
    38: "TB-TG1467301_L008"
    39: "TB-TG1465257_L008"
    40: "TB-TG1465141_L008"
    41: "TB-TG1465191_L008"
    42: "TB-TG1465827_L008"
    43: "TB-TG1466061_L008"
    44: "TB_TG1466401_S104_L001"
    45: "TB_TG1466351_S84_L001"
    46: "TB-TG1465549_L008"
    47: "TB-TG1467307_L008"
    48: "TB-TG1465091_L008"
    49: "TB-TG1465049_L008"
