samples:
    0: "TB_TG1466167_S21_L001"
    1: "TB-TG1465945_L008"
    2: "TB_TG1466575_S178_L001"
    3: "TB_TG1466211_S35_L001"
    4: "TB_TG1466525_S158_L001"
    5: "TB-TG1467273_L008"
    6: "TB-TG1467507_L008"
    7: "TB-TG1465777_L008"
    8: "TB_TG1466605_S188_L001"
    9: "TB-TG1465113_L008"
    10: "TB-TG1465875_L008"
    11: "TB-TG1465873_L008"
    12: "TB_TG1466585_S180_L001"
    13: "TB-TG1465559_L008"
    14: "TB-TG1461483_L008"
    15: "TB-TG1466009_L008"
    16: "TB-TG1467251_L008"
    17: "TB-TG1465895_L008"
    18: "TB-TG1465527_L008"
    19: "TB-TG1465507_L008"
    20: "TB-TG1465519_L008"
    21: "TB-TG1465961_L008"
    22: "TB-TG1465487_L008"
    23: "TB-TG1467337_L008"
    24: "TB-TG1467421_L008"
    25: "TB_TG1466305_S66_L001"
    26: "TB-TG1465009_L008"
    27: "TB-TG1464979_L008"
    28: "TB-TG1465815_L008"
    29: "TB_TG1466185_S26_L001"
    30: "TB-TG1467435_L008"
    31: "TB_TG1466403_S105_L001"
    32: "TB-TG1465915_L008"
    33: "TB_TG1466363_S89_L001"
    34: "TB-TG1461697_L008"
    35: "TB-TG1461765_L008"
    36: "TB-TG1465143_L008"
    37: "TB-TG1465099_L008"
    38: "TB-TG1466023_L008"
    39: "TB_TG1466123_S7_L001"
    40: "TB-TG1464991_L008"
    41: "TB_TG1466493_S145_L001"
    42: "TB-TG1465021_L008"
    43: "TB-TG1467455_L008"
    44: "TB-TG1461651_L008"
    45: "TB-TG1461629_L008"
    46: "TB-TG1465007_L008"
    47: "TB_TG1466445_S125_L001"
    48: "TB_TG1466119_S6_L001"
    49: "TB_TG1466413_S110_L001"
