samples:
    0: "TB-TG1465969_L008"
    1: "TB-TG1467465_L008"
    2: "TB_TG1466173_S23_L001"
    3: "TB-TG1464981_L008"
    4: "TB_TG1466553_S169_L001"
    5: "TB-TG1461531_L008"
    6: "TB-TG1461453_L008"
    7: "TB-TG1465131_L008"
    8: "TB-TG1465889_L008"
    9: "TB-TG1467331_L008"
    10: "TB-TG1461749_L008"
    11: "TB_TG1466673_S217_L001"
    12: "TB-TG1465155_L008"
    13: "TB-TG1461633_L008"
    14: "TB-TG1467269_L008"
    15: "TB-TG1467295_L008"
    16: "TB-TG1466105_L008"
    17: "TB-TG1466075_L008"
    18: "TB_TG1466175_S24_L001"
    19: "TB-TG1467375_L008"
    20: "TB-TG1466103_L008"
    21: "TB_TG1466187_S27_L001"
    22: "TB-TG1461699_L008"
    23: "TB-TG1465255_L008"
    24: "TB-TG1465773_L008"
    25: "TB-TG1467489_L008"
    26: "TB_TG1466663_S213_L001"
    27: "TB-TG1461731_L008"
    28: "TB_TG1466247_S46_L001"
    29: "TB-TG1461545_L008"
    30: "TB-TG1465963_L008"
    31: "TB_TG1466311_S69_L001"
    32: "TB-TG1465927_L008"
    33: "TB-TG1461529_L008"
    34: "TB-TG1467319_L008"
    35: "TB-TG1465217_L008"
    36: "TB_TG1466133_S11_L001"
    37: "TB-TG1465077_L008"
    38: "TB-TG1465981_L008"
    39: "TB-TG1466069_L008"
    40: "TB-TG1461639_L008"
    41: "TB_TG1466309_S68_L001"
    42: "TB_TG1466429_S117_L001"
    43: "TB-TG1465085_L008"
    44: "TB-TG1465935_L008"
    45: "TB_TG1466513_S152_L001"
    46: "TB_TG1466353_S85_L001"
    47: "TB-TG1467333_L008"
    48: "TB-TG1465463_L008"
    49: "TB_TG1466335_S81_L001"
