samples:
    0: "TB-TG1467485_L008"
    1: "TB-TG1465965_L008"
    2: "TB-TG1467423_L008"
    3: "TB-TG1461705_L008"
    4: "TB-TG1465879_L008"
    5: "TB_TG1466131_S10_L001"
    6: "TB-TG1465529_L008"
    7: "TB-TG1461571_L008"
    8: "TB_TG1466399_S103_L001"
    9: "TB-TG1465835_L008"
    10: "TB-TG1465163_L008"
    11: "TB-TG1467297_L008"
    12: "TB-TG1465883_L008"
    13: "TB_TG1466665_S214_L001"
    14: "TB-TG1465943_L008"
    15: "TB_TG1466547_S167_L001"
    16: "TB-TG1466027_L008"
    17: "TB-TG1465181_L008"
    18: "TB_TG1466201_S33_L001"
    19: "TB-TG1461717_L008"
    20: "TB-TG1467369_L008"
    21: "TB-TG1461565_L008"
    22: "TB_TG1466519_S155_L001"
    23: "TB_TG1466641_S204_L001"
    24: "TB-TG1464977_L008"
    25: "TB-TG1465145_L008"
    26: "TB-TG1461673_L008"
    27: "TB-TG1465193_L008"
    28: "TB-TG1465925_L008"
    29: "TB_TG1466315_S71_L001"
    30: "TB_TG1466523_S157_L001"
    31: "TB_TG1466637_S202_L001"
    32: "TB-TG1461737_L008"
    33: "TB_TG1466193_S30_L001"
    34: "TB-TG1461547_L008"
    35: "TB-TG1461715_L008"
    36: "TB-TG1465197_L008"
    37: "TB-TG1465279_L008"
    38: "TB-TG1465855_L008"
    39: "TB-TG1461675_L008"
    40: "TB_TG1466107_S1_L001"
    41: "TB_TG1466317_S72_L001"
    42: "TB_TG1466323_S75_L001"
    43: "TB-TG1467345_L008"
    44: "TB_tg1461611_S8_L001"
    45: "TB-TG1461719_L008"
    46: "TB-TG1467365_L008"
    47: "TB_TG1466267_S55_L001"
    48: "TB-TG1467473_L008"
    49: "TB-TG1465201_L008"
