samples:
    0: "TB-TG1466057_L008"
    1: "TB_tg1461617_S11_L001"
    2: "TB_TG1466367_S91_L001"
    3: "TB-TG1467293_L008"
    4: "TB-TG1465003_L008"
    5: "TB-TG1464969_L008"
    6: "TB-TG1461653_L008"
    7: "TB_TG1466137_S13_L001"
    8: "TB-TG1465525_L008"
    9: "TB-TG1467445_L008"
    10: "TB-TG1465481_L008"
    11: "TB_TG1466387_S99_L001"
    12: "TB_tg1461605_S5_L001"
    13: "TB_TG1466409_S108_L001"
    14: "TB-TG1465101_L008"
    15: "TB-TG1466011_L008"
    16: "TB-TG1466035_L008"
    17: "TB-TG1465013_L008"
    18: "TB-TG1465843_L008"
    19: "TB_TG1466313_S70_L001"
    20: "TB-TG1467287_L008"
    21: "TB-TG1467419_L008"
    22: "TB_TG1466125_S8_L001"
    23: "TB_TG1466541_S165_L001"
    24: "TB_TG1466277_S58_L001"
    25: "TB_TG1466431_S118_L001"
    26: "TB-TG1466005_L008"
    27: "TB-TG1465593_L008"
    28: "TB-TG1465791_L008"
    29: "TB-TG1464967_L008"
    30: "TB-TG1461649_L008"
    31: "TB-TG1466001_L008"
    32: "TB_tg1461627_S15_L001"
    33: "TB-TG1465871_L008"
    34: "TB-TG1464995_L008"
    35: "TB-TG1465491_L008"
    36: "TB-TG1465111_L008"
    37: "TB-TG1465015_L008"
    38: "TB-TG1465127_L008"
    39: "TB-TG1465005_L008"
    40: "TB-TG1466083_L008"
    41: "TB_TG1466495_S146_L001"
    42: "TB-TG1465523_L008"
    43: "TB-TG1461513_L008"
    44: "TB-TG1466013_L008"
    45: "TB-TG1465115_L008"
    46: "TB-TG1461553_L008"
    47: "TB_TG1466473_S138_L001"
    48: "TB-TG1465893_L008"
    49: "TB-TG1465135_L008"
