samples:
    0: "TB-TG1465451_L008"
    1: "TB-TG1465503_L008"
    2: "TB_TG1466299_S64_L001"
    3: "TB-TG1461703_L008"
    4: "TB-TG1461711_L008"
    5: "TB-TG1465011_L008"
    6: "TB-TG1466021_L008"
    7: "TB_TG1466157_S18_L001"
    8: "TB_TG1466533_S161_L001"
    9: "TB-TG1461489_L008"
    10: "TB-TG1461581_L008"
    11: "TB_TG1466433_S119_L001"
    12: "TB-TG1465499_L008"
    13: "TB-TG1465975_L008"
    14: "TB-TG1465089_L008"
    15: "TB-TG1467275_L008"
    16: "TB_TG1466615_S192_L001"
    17: "TB-TG1466085_L008"
    18: "TB-TG1465125_L008"
    19: "TB-TG1461469_L008"
    20: "TB_TG1466621_S195_L001"
    21: "TB-TG1466039_L008"
    22: "TB-TG1461759_L008"
    23: "TB_TG1466279_S59_L001"
    24: "TB-TG1465605_L008"
    25: "TB-TG1465885_L008"
    26: "TB-TG1465035_L008"
    27: "TB-TG1466041_L008"
    28: "TB-TG1461657_L008"
    29: "TB-TG1466059_L008"
    30: "TB-TG1461523_L008"
    31: "TB_TG1466349_S83_L001"
    32: "TB-TG1467371_L008"
    33: "TB-TG1465603_L008"
    34: "TB-TG1467381_L008"
    35: "TB-TG1461509_L008"
    36: "TB-TG1465225_L008"
    37: "TB-TG1465601_L008"
    38: "TB-TG1461451_L008"
    39: "TB-TG1465205_L008"
    40: "TB_TG1466219_S39_L001"
    41: "TB-TG1467501_L008"
    42: "TB-TG1465207_L008"
    43: "TB-TG1466079_L008"
    44: "TB_TG1466407_S107_L001"
    45: "TB_TG1466435_S120_L001"
    46: "TB-TG1467373_L008"
    47: "TB-TG1461723_L008"
    48: "TB_TG1466273_S57_L001"
    49: "TB_TG1466447_S126_L001"
