samples:
    0: "TB-TG1465107_L008"
    1: "TB-TG1465781_L008"
    2: "TB_TG1466651_S207_L001"
    3: "TB-TG1465799_L008"
    4: "TB_tg1461599_S3_L001"
    5: "TB-TG1465161_L008"
    6: "TB-TG1465845_L008"
    7: "TB-TG1466037_L008"
    8: "TB-TG1465051_L008"
    9: "TB-TG1465221_L008"
    10: "TB-TG1465817_L008"
    11: "TB-TG1467357_L008"
    12: "TB_tg1461609_S7_L001"
    13: "TB-TG1461745_L008"
    14: "TB-TG1465513_L008"
    15: "TB-TG1466045_L008"
    16: "TB-TG1465475_L008"
    17: "TB_TG1466217_S38_L001"
    18: "TB-TG1461635_L008"
    19: "TB-TG1465785_L008"
    20: "TB-TG1465087_L008"
    21: "TB-TG1466077_L008"
    22: "TB_TG1466381_S96_L001"
    23: "TB-TG1461467_L008"
    24: "TB-TG1466051_L008"
    25: "TB-TG1461733_L008"
    26: "TB_TG1466281_S60_L001"
    27: "TB-TG1461589_L008"
    28: "TB-TG1465473_L008"
    29: "TB-TG1465535_L008"
    30: "TB_tg1461615_S10_L001"
    31: "TB-TG1461679_L008"
    32: "TB-TG1461727_L008"
    33: "TB-TG1465239_L008"
    34: "TB-TG1465471_L008"
    35: "TB-TG1465587_L008"
    36: "TB-TG1465103_L008"
    37: "TB_TG1466417_S112_L001"
    38: "TB_TG1466579_S179_L001"
    39: "TB-TG1467265_L008"
    40: "TB-TG1467499_L008"
    41: "TB-TG1465577_L008"
    42: "TB-TG1465129_L008"
    43: "TB-TG1465591_L008"
    44: "TB-TG1465869_L008"
    45: "TB_TG1466531_S160_L001"
    46: "TB_TG1466301_S65_L001"
    47: "TB-TG1465599_L008"
    48: "TB_tg1461613_S9_L001"
    49: "TB-TG1465247_L008"
