samples:
    0: "COMBINED_TG1467107"
    1: "COMBINED_TG1466207"
    2: "COMBINED_TG1467463"
    3: "COMBINED_TG1467047"
    4: "COMBINED_TG1466291"
    5: "COMBINED_TG1465119"
    6: "COMBINED_TG1466129"
    7: "COMBINED_TG1466877"
    8: "COMBINED_TG1467519"
    9: "COMBINED_TG1467087"
    10: "COMBINED_TG1465801"
    11: "COMBINED_TG1467419"
    12: "COMBINED_TG1467495"
    13: "COMBINED_TG1466943"
    14: "COMBINED_TG1465971"
    15: "COMBINED_TG1465823"
    16: "COMBINED_TG1467319"
    17: "COMBINED_TG1466177"
    18: "COMBINED_TG1466875"
    19: "COMBINED_TG1466861"
    20: "COMBINED_TG1465063"
    21: "COMBINED_TG1466711"
    22: "COMBINED_TG1466905"
    23: "COMBINED_TG1466961"
    24: "COMBINED_TG1467093"
    25: "COMBINED_TG1466525"
    26: "COMBINED_TG1465159"
    27: "COMBINED_TG1465531"
    28: "COMBINED_TG1466545"
    29: "COMBINED_TG1465025"
    30: "COMBINED_TG1467203"
    31: "COMBINED_TG1465183"
    32: "COMBINED_TG1466805"
    33: "COMBINED_TG1466531"
    34: "COMBINED_TG1467413"
    35: "COMBINED_TG1467089"
    36: "COMBINED_TG1467133"
    37: "COMBINED_TG1466855"
    38: "COMBINED_TG1466341"
    39: "COMBINED_TG1466577"
    40: "COMBINED_TG1467199"
    41: "COMBINED_TG1467301"
    42: "COMBINED_TG1466197"
    43: "COMBINED_TG1466231"
    44: "COMBINED_TG1465123"
    45: "COMBINED_TG1467059"
    46: "COMBINED_TG1464993"
    47: "COMBINED_TG1465539"
    48: "COMBINED_TG1465795"
    49: "COMBINED_TG1466019"
