samples:
    0: "COMBINED_TG1467073"
    1: "COMBINED_TG1465559"
    2: "COMBINED_TG1465811"
    3: "COMBINED_TG1467313"
    4: "COMBINED_TG1465821"
    5: "COMBINED_TG1466149"
    6: "COMBINED_TG1466777"
    7: "COMBINED_TG1465033"
    8: "COMBINED_TG1465133"
    9: "COMBINED_TG1466501"
    10: "COMBINED_TG1466899"
    11: "COMBINED_TG1465125"
    12: "COMBINED_TG1464971"
    13: "COMBINED_TG1466161"
    14: "COMBINED_TG1465913"
    15: "COMBINED_TG1466139"
    16: "COMBINED_TG1466243"
    17: "COMBINED_TG1467137"
    18: "COMBINED_TG1467021"
    19: "COMBINED_TG1466583"
    20: "COMBINED_TG1465875"
    21: "COMBINED_TG1465473"
    22: "COMBINED_TG1466287"
    23: "COMBINED_TG1466337"
    24: "COMBINED_TG1467411"
    25: "COMBINED_TG1465177"
    26: "COMBINED_TG1466803"
    27: "COMBINED_TG1466979"
    28: "COMBINED_TG1467111"
    29: "COMBINED_TG1464983"
    30: "COMBINED_TG1466043"
    31: "COMBINED_TG1465477"
    32: "COMBINED_TG1466957"
    33: "COMBINED_TG1466717"
    34: "COMBINED_TG1467435"
    35: "COMBINED_TG1467245"
    36: "COMBINED_TG1466823"
    37: "COMBINED_TG1466543"
    38: "COMBINED_TG1465005"
    39: "COMBINED_TG1466569"
    40: "COMBINED_TG1466389"
    41: "COMBINED_TG1466933"
    42: "COMBINED_TG1465017"
    43: "COMBINED_TG1467189"
    44: "COMBINED_TG1465595"
    45: "COMBINED_TG1466457"
    46: "COMBINED_TG1466165"
    47: "COMBINED_TG1466479"
    48: "COMBINED_TG1466601"
    49: "COMBINED_TG1466553"
