batch: "2"
samples:
    0: "TB_TG1467139_S172_L001"
    1: "TB_TG1466701_S8_L001"
    2: "TB_TG1467083_S154_L001"
    3: "TB_TG1466203_S76_L001"
    4: "TB_TG1466807_S46_L001"
    5: "TB_TG1466789_S39_L001"
    6: "TB_TG1466903_S83_L001"
    7: "TB_TG1466691_S4_L001"
    8: "TB_TG1467161_S183_L001"
    9: "TB_TG1467043_S142_L001"
    10: "TB_TG1466917_S89_L001"
    11: "TB_TG1466859_S67_L001"
    12: "TB_TG1466159_S69_L001"
    13: "TB_TG1466871_S71_L001"
    14: "TB_TG1466715_S11_L001"
    15: "TB_TG1466775_S35_L001"
    16: "TB_TG1467041_S161_L001"
    17: "TB_TG1467231_S211_L001"
    18: "TB_TG1466909_S86_L001"
    19: "TB_TG1466759_S27_L001"
    20: "TB_TG1467103_S159_L001"
    21: "TB_TG1466767_S31_L001"
    22: "TB_TG1466697_S132_L001"
    23: "TB_TG1467143_S174_L001"
    24: "TB_TG1466819_S50_L001"
    25: "TB_TG1466833_S56_L001"
    26: "TB_TG1466685_S131_L001"
    27: "TB_TG1467219_S205_L001"
    28: "TB_TG1466813_S49_L001"
    29: "TB_TG1466969_S111_L001"
    30: "TB_TG1467217_S204_L001"
    31: "TB_TG1466779_S143_L001"
    32: "TB_TG1466687_S2_L001"
    33: "TB_TG1467017_S133_L001"
    34: "TB_TG1466973_S113_L001"
    35: "TB_TG1467013_S131_L001"
    36: "TB_TG1467121_S166_L001"
    37: "TB_TG1466947_S102_L001"
    38: "TB_TG1467141_S173_L001"
    39: "TB_TG1466965_S109_L001"
    40: "TB_TG1466927_S94_L001"
    41: "TB_TG1467117_S164_L001"
    42: "TB_TG1466233_S82_L001"
    43: "TB_TG1466771_S33_L001"
    44: "TB_TG1466787_S38_L001"
    45: "TB_TG1466837_S58_L001"
    46: "TB_TG1467229_S210_L001"
    47: "TB_TG1466997_S124_L001"
    48: "TB_TG1466847_S63_L001"
    49: "TB_TG1466801_S43_L001"
    50: "TB_TG1467061_S148_L001"
    51: "TB_TG1467035_S140_L001"
    52: "TB_TG1466975_S114_L001"
    53: "TB_TG1467131_S169_L001"
    54: "TB_TG1466765_S30_L001"
    55: "TB_TG1466731_S15_L001"
    56: "TB_TG1466991_S121_L001"
    57: "TB_TG1466953_S105_L001"
    58: "TB_TG1466237_S83_L001"
    59: "TB_TG1466989_S120_L001"
    60: "TB_TG1467005_S128_L001"
    61: "TB_TG1466923_S92_L001"
    62: "TB_TG1467077_S151_L001"
    63: "TB_TG1466705_S134_L001"
    64: "TB_TG1466785_S37_L001"
    65: "TB_TG1466901_S82_L001"
    66: "TB_TG1467239_S215_L001"
    67: "TB_TG1466865_S148_L001"
    68: "TB_TG1466825_S146_L001"
    69: "TB_TG1467175_S188_L001"
    70: "TB_TG1467243_S217_L001"
    71: "TB_TG1466985_S118_L001"
    72: "TB_TG1467015_S132_L001"
    73: "TB_TG1467007_S129_L001"
    74: "TB_TG1467029_S138_L001"
    75: "TB_TG1466951_S104_L001"
    76: "TB_TG1467049_S144_L001"
    77: "TB_TG1467129_S168_L001"
    78: "TB_TG1467165_S184_L001"
    79: "TB_TG1466745_S21_L001"
    80: "TB_TG1467235_S213_L001"
    81: "TB_TG1466793_S41_L001"
    82: "TB_TG1467045_S143_L001"
    83: "TB_TG1466843_S61_L001"
    84: "TB_TG1467109_S160_L001"
    85: "TB_TG1467193_S195_L001"
    86: "TB_TG1466681_S129_L001"
    87: "TB_TG1467207_S200_L001"
    88: "TB_TG1466925_S93_L001"
    89: "TB_TG1466941_S100_L001"
    90: "TB_TG1466751_S24_L001"
    91: "TB_TG1467169_S186_L001"
    92: "TB_TG1467119_S165_L001"
    93: "TB_TG1466829_S54_L001"
    94: "TB_TG1466761_S28_L001"
    95: "TB_TG1466773_S34_L001"
    96: "TB_TG1466869_S70_L001"
    97: "TB_TG1466879_S132_L001"
    98: "TB_TG1466729_S14_L001"
    99: "TB_TG1466993_S122_L001"
    100: "TB_TG1467075_S150_L001"
    101: "TB_TG1467091_S157_L001"
    102: "TB_TG1467155_S180_L001"
    103: "TB_TG1466755_S26_L001"
    104: "TB_TG1466867_S101_L001"
    105: "TB_TG1466839_S59_L001"
    106: "TB_TG1466853_S147_L001"
    107: "TB_TG1466897_S81_L001"
    108: "TB_TG1467213_S202_L001"
    109: "TB_TG1467031_S139_L001"
    110: "TB_TG1467037_S141_L001"
    111: "TB_TG1467019_S134_L001"
    112: "TB_TG1466713_S10_L001"
    113: "TB_TG1466709_S9_L001"
    114: "TB_TG1467027_S137_L001"
    115: "TB_TG1466707_S135_L001"
    116: "TB_TG1466841_S60_L001"
    117: "TB_TG1467221_S206_L001"
    118: "TB_TG1467125_S13_L001"
    119: "TB_TG1466677_S1_L001"
    120: "TB_TG1466741_S20_L001"
    121: "TB_TG1467151_S178_L001"
    122: "TB_TG1467197_S197_L001"
    123: "TB_TG1466699_S7_L001"
    124: "TB_TG1466781_S36_L001"
    125: "TB_TG1466945_S101_L001"
    126: "TB_TG1467223_S207_L001"
    127: "TB_TG1466949_S103_L001"
    128: "TB_TG1466275_S88_L001"
    129: "TB_TG1467085_S155_L001"
    130: "TB_TG1466821_S51_L001"
    131: "TB_TG1467067_S149_L001"
    132: "TB_TG1466893_S80_L001"
    133: "TB_TG1467159_S182_L001"
    134: "TB_TG1466743_S140_L001"
    135: "TB_TG1466883_S76_L001"
    136: "TB_TG1466817_S145_L001"
    137: "TB_TG1467009_S130_L001"
    138: "TB_TG1466795_S42_L001"
    139: "TB_TG1466907_S85_L001"
    140: "TB_TG1467215_S203_L001"
    141: "TB_TG1467057_S147_L001"
    142: "TB_TG1466725_S13_L001"
    143: "TB_TG1466735_S17_L001"
    144: "TB_TG1466811_S48_L001"
    145: "TB_TG1467039_S160_L001"
    146: "TB_TG1466915_S88_L001"
    147: "TB_TG1467023_S135_L001"
    148: "TB_TG1467079_S152_L001"
    149: "TB_TG1467195_S196_L001"
    150: "TB_TG1466845_S62_L001"
    151: "TB_TG1466607_S123_L001"
    152: "TB_TG1466749_S23_L001"
    153: "TB_TG1466851_S65_L001"
    154: "TB_TG1466959_S107_L001"
    155: "TB_TG1466999_S125_L001"
    156: "TB_TG1467157_S181_L001"
    157: "TB_TG1466939_S99_L001"
    158: "TB_TG1467095_S10_L001"
    159: "TB_TG1466857_S66_L001"
    160: "TB_TG1466703_S133_L001"
    161: "TB_TG1466747_S22_L001"
    162: "TB_TG1466763_S29_L001"
    163: "TB_TG1466831_S55_L001"
    164: "TB_TG1466783_S144_L001"
    165: "TB_TG1466689_S3_L001"
    166: "TB_TG1466929_S95_L001"
    167: "TB_TG1466737_S18_L001"
    168: "TB_TG1466739_S19_L001"
    169: "TB_TG1467025_S136_L001"
    170: "TB_TG1466931_S96_L001"
    171: "TB_TG1466977_S115_L001"
    172: "TB_TG1466995_S123_L001"
    173: "TB_TG1466885_S77_L001"
    174: "TB_TG1467149_S177_L001"
    175: "TB_TG1466809_S47_L001"
    176: "TB_TG1467205_S199_L001"
    177: "TB_TG1467127_S167_L001"
    178: "TB_TG1467145_S175_L001"
    179: "TB_TG1467187_S194_L001"
    180: "TB_TG1466937_S98_L001"
    181: "TB_TG1466919_S90_L001"
    182: "TB_TG1467201_S198_L001"
    183: "TB_TG1466695_S6_L001"
    184: "TB_TG1466849_S64_L001"
    185: "TB_TG1466719_S137_L001"
    186: "TB_TG1466921_S91_L001"
    187: "TB_TG1466987_S119_L001"
    188: "TB_TG1466981_S116_L001"
    189: "TB_TG1467001_S126_L001"
    190: "TB_TG1466733_S16_L001"
    191: "TB_TG1467147_S176_L001"
    192: "TB_TG1467177_S189_L001"
    193: "TB_TG1467237_S214_L001"
    194: "TB_TG1466753_S25_L001"
    195: "TB_TG1467055_S146_L001"
    196: "TB_TG1466873_S72_L001"
    197: "TB_TG1466757_S141_L001"
    198: "TB_TG1466967_S110_L001"
    199: "TB_TG1467003_S127_L001"
    200: "TB_TG1466863_S69_L001"
    201: "TB_TG1466971_S112_L001"
    202: "TB_TG1466835_S57_L001"
    203: "TB_TG1466911_S87_L001"
    204: "TB_TG1466827_S53_L001"
    205: "TB_TG1466721_S138_L001"
    206: "TB_TG1466963_S108_L001"
    207: "TB_TG1466955_S106_L001"
    208: "TB_TG1466693_S5_L001"
    209: "TB_TG1466983_S117_L001"
    210: "TB_TG1467171_S187_L001"
    211: "TB_TG1467167_S185_L001"
    212: "TB_TG1467081_S153_L001"
    213: "TB_TG1467225_S208_L001"
    214: "TB_TG1466769_S32_L001"
    215: "TB_TG1467053_S145_L001"
    216: "TB_TG1466571_S117_L001"
    217: "TB_TG1467241_S216_L001"
    218: "TB_TG1467113_S162_L001"
    219: "TB_TG1466891_S79_L001"
    220: "TB_TG1466679_S128_L001"
    221: "TB_TG1466935_S97_L001"
    222: "TB_TG1466887_S78_L001"
