batch: "3"
samples:
    0: "COMBINED_TG1465177"
    1: "COMBINED_TG1466221"
    2: "COMBINED_TG1464979"
    3: "COMBINED_TG1466557"
    4: "COMBINED_TG1467093"
    5: "COMBINED_TG1466495"
    6: "COMBINED_TG1466545"
    7: "COMBINED_TG1466265"
    8: "COMBINED_TG1465071"
    9: "COMBINED_TG1467153"
    10: "COMBINED_TG1466467"
    11: "COMBINED_TG1466479"
    12: "COMBINED_TG1467133"
    13: "COMBINED_TG1466581"
    14: "COMBINED_TG1466645"
    15: "COMBINED_TG1466487"
    16: "COMBINED_TG1465539"
    17: "COMBINED_TG1465965"
    18: "COMBINED_TG1466113"
    19: "COMBINED_TG1467179"
    20: "COMBINED_TG1466293"
    21: "COMBINED_TG1465001"
    22: "COMBINED_TG1467071"
    23: "COMBINED_TG1465843"
    24: "COMBINED_TG1465969"
    25: "COMBINED_TG1466711"
    26: "COMBINED_TG1467209"
    27: "COMBINED_TG1466499"
    28: "COMBINED_TG1465569"
    29: "COMBINED_TG1466223"
    30: "COMBINED_TG1467227"
    31: "COMBINED_TG1466003"
    32: "COMBINED_TG1466961"
    33: "COMBINED_TG1465541"
    34: "COMBINED_TG1461471"
    35: "COMBINED_TG1466855"
    36: "COMBINED_TG1465033"
    37: "COMBINED_TG1465069"
    38: "COMBINED_TG1465481"
    39: "COMBINED_TG1466303"
    40: "COMBINED_TG1466373"
    41: "COMBINED_TG1466523"
    42: "COMBINED_TG1467463"
    43: "COMBINED_TG1467069"
    44: "COMBINED_TG1466061"
    45: "COMBINED_TG1466501"
    46: "COMBINED_TG1467065"
    47: "COMBINED_TG1465183"
    48: "COMBINED_TG1465823"
    49: "COMBINED_TG1465841"
    50: "COMBINED_TG1465885"
    51: "COMBINED_TG1466241"
    52: "COMBINED_TG1467191"
    53: "COMBINED_TG1466957"
    54: "COMBINED_TG1464985"
    55: "COMBINED_TG1467107"
    56: "COMBINED_TG1465045"
    57: "COMBINED_TG1466067"
    58: "COMBINED_TG1465123"
    59: "COMBINED_TG1466155"
    60: "COMBINED_TG1467111"
    61: "COMBINED_TG1466895"
    62: "COMBINED_TG1467185"
    63: "COMBINED_TG1467033"
    64: "COMBINED_TG1465603"
    65: "COMBINED_TG1464989"
    66: "COMBINED_TG1466799"
    67: "COMBINED_TG1465153"
    68: "COMBINED_TG1465025"
    69: "COMBINED_TG1466675"
    70: "COMBINED_TG1467495"
    71: "COMBINED_TG1464973"
    72: "COMBINED_TG1465913"
    73: "COMBINED_TG1465971"
    74: "COMBINED_TG1467519"
    75: "COMBINED_TG1467089"
    76: "COMBINED_TG1467313"
    77: "COMBINED_TG1465159"
    78: "COMBINED_TG1465801"
    79: "COMBINED_TG1466047"
    80: "COMBINED_TG1466877"
    81: "COMBINED_TG1466635"
    82: "COMBINED_TG1466153"
    83: "COMBINED_TG1466727"
    84: "COMBINED_TG1465887"
    85: "COMBINED_TG1466209"
    86: "COMBINED_TG1465157"
    87: "COMBINED_TG1467051"
    88: "COMBINED_TG1465119"
    89: "COMBINED_TG1465167"
    90: "COMBINED_TG1466717"
    91: "COMBINED_TG1466371"
    92: "COMBINED_TG1465861"
    93: "COMBINED_TG1467363"
    94: "COMBINED_TG1467183"
    95: "COMBINED_TG1467115"
    96: "COMBINED_TG1467199"
    97: "COMBINED_TG1466503"
    98: "COMBINED_TG1464991"
    99: "COMBINED_TG1466933"
    100: "COMBINED_TG1465191"
    101: "COMBINED_TG1465869"
    102: "COMBINED_TG1466197"
    103: "COMBINED_TG1466527"
    104: "COMBINED_TG1465017"
    105: "COMBINED_TG1465593"
    106: "COMBINED_TG1466025"
    107: "COMBINED_TG1466457"
    108: "COMBINED_TG1466339"
    109: "COMBINED_TG1465473"
    110: "COMBINED_TG1466529"
    111: "COMBINED_TG1467047"
    112: "COMBINED_TG1467301"
    113: "COMBINED_TG1467335"
    114: "COMBINED_TG1465125"
    115: "COMBINED_TG1467245"
    116: "COMBINED_TG1465477"
    117: "COMBINED_TG1465847"
    118: "COMBINED_TG1464993"
    119: "COMBINED_TG1466387"
    120: "COMBINED_TG1465005"
    121: "COMBINED_TG1466423"
    122: "COMBINED_TG1466139"
    123: "COMBINED_TG1466207"
    124: "COMBINED_TG1466683"
    125: "COMBINED_TG1466803"
    126: "COMBINED_TG1466979"
    127: "COMBINED_TG1467203"
    128: "COMBINED_TG1467211"
    129: "COMBINED_TG1467413"
    130: "COMBINED_TG1465799"
    131: "COMBINED_TG1466547"
    132: "COMBINED_TG1467135"
    133: "COMBINED_TG1467087"
    134: "COMBINED_TG1466899"
    135: "COMBINED_TG1466797"
    136: "COMBINED_TG1466149"
    137: "COMBINED_TG1465039"
    138: "COMBINED_TG1466183"
    139: "COMBINED_TG1466905"
    140: "COMBINED_TG1467163"
    141: "COMBINED_TG1467233"
    142: "COMBINED_TG1466345"
    143: "COMBINED_TG1465811"
    144: "COMBINED_TG1465531"
    145: "COMBINED_TG1467435"
    146: "COMBINED_TG1465091"
    147: "COMBINED_TG1465999"
    148: "COMBINED_TG1466723"
    149: "COMBINED_TG1467137"
    150: "COMBINED_TG1466269"
    151: "COMBINED_TG1467417"
    152: "COMBINED_TG1466389"
    153: "COMBINED_TG1466165"
    154: "COMBINED_TG1464987"
    155: "COMBINED_TG1466881"
    156: "COMBINED_TG1466875"
    157: "COMBINED_TG1467411"
    158: "COMBINED_TG1467415"
    159: "COMBINED_TG1466805"
    160: "COMBINED_TG1466001"
    161: "COMBINED_TG1467105"
    162: "COMBINED_TG1465487"
    163: "COMBINED_TG1465863"
    164: "COMBINED_TG1466171"
    165: "COMBINED_TG1466291"
    166: "COMBINED_TG1466551"
    167: "COMBINED_TG1466815"
    168: "COMBINED_TG1466601"
    169: "COMBINED_TG1467123"
    170: "COMBINED_TG1466225"
    171: "COMBINED_TG1466791"
    172: "COMBINED_TG1466943"
    173: "COMBINED_TG1465867"
    174: "COMBINED_TG1464999"
    175: "COMBINED_TG1465595"
    176: "COMBINED_TG1466027"
    177: "COMBINED_TG1467181"
    178: "COMBINED_TG1466141"
    179: "COMBINED_TG1467097"
    180: "COMBINED_TG1464981"
    181: "COMBINED_TG1466535"
    182: "COMBINED_TG1466589"
    183: "COMBINED_TG1466393"
    184: "COMBINED_TG1465821"
    185: "COMBINED_TG1467101"
    186: "COMBINED_TG1467073"
    187: "COMBINED_TG1465089"
    188: "COMBINED_TG1467099"
    189: "COMBINED_TG1466231"
    190: "COMBINED_TG1465133"
    191: "COMBINED_TG1466161"
    192: "COMBINED_TG1466583"
    193: "COMBINED_TG1465063"
    194: "COMBINED_TG1466525"
    195: "COMBINED_TG1466177"
    196: "COMBINED_TG1465121"
    197: "COMBINED_TG1465953"
    198: "COMBINED_TG1466359"
    199: "COMBINED_TG1466569"
    200: "COMBINED_TG1466543"
    201: "COMBINED_TG1466889"
    202: "COMBINED_TG1466285"
    203: "COMBINED_TG1467319"
    204: "COMBINED_TG1466181"
    205: "COMBINED_TG1461679"
    206: "COMBINED_TG1466861"
    207: "COMBINED_TG1464983"
    208: "COMBINED_TG1465973"
    209: "COMBINED_TG1467407"
    210: "COMBINED_TG1465875"
    211: "COMBINED_TG1466777"
    212: "COMBINED_TG1466019"
    213: "COMBINED_TG1466289"
    214: "COMBINED_TG1466553"
    215: "COMBINED_TG1466497"
    216: "COMBINED_TG1465559"
    217: "COMBINED_TG1466531"
    218: "COMBINED_TG1467021"
    219: "COMBINED_TG1467419"
    220: "COMBINED_TG1467011"
    221: "COMBINED_TG1467507"
    222: "COMBINED_TG1466129"
    223: "COMBINED_TG1466005"
    224: "COMBINED_TG1466337"
    225: "COMBINED_TG1466667"
    226: "COMBINED_TG1461519"
    227: "COMBINED_TG1464995"
    228: "COMBINED_TG1464967"
    229: "COMBINED_TG1465509"
    230: "COMBINED_TG1466913"
    231: "COMBINED_TG1467173"
    232: "COMBINED_TG1466647"
    233: "COMBINED_TG1464971"
    234: "COMBINED_TG1466243"
    235: "COMBINED_TG1467409"
    236: "COMBINED_TG1466577"
    237: "COMBINED_TG1466341"
    238: "COMBINED_TG1465011"
    239: "COMBINED_TG1466475"
    240: "COMBINED_TG1465093"
    241: "COMBINED_TG1466043"
    242: "COMBINED_TG1466051"
    243: "COMBINED_TG1466287"
    244: "COMBINED_TG1466343"
    245: "COMBINED_TG1467189"
    246: "COMBINED_TG1465061"
    247: "COMBINED_TG1467059"
    248: "COMBINED_TG1466823"
    249: "COMBINED_TG1465803"
    250: "COMBINED_TG1467063"
    251: "COMBINED_TG1465795"
