batch: "0"
samples:
    0: "4982_L003"
    1: "825_L003"
    2: "8541_L003"
    3: "6213_L004"
    4: "8559_L003"
    5: "18105_L003"
    6: "11097_L003"
    7: "2088_L004"
    8: "2013-5189_L003"
    9: "280_L003"
