batch: "1"
samples:
    0: "TB-TG1465803_L008"
    1: "TB-TG1467411_L008"
    2: "TB_TG1466565_S175_L001"
    3: "TB_TG1466617_S193_L001"
    4: "TB-TG1465505_L008"
    5: "TB-TG1466003_L008"
    6: "TB-TG1467413_L008"
    7: "TB-TG1467437_L008"
    8: "TB-TG1465239_L008"
    9: "TB-TG1465057_L008"
