batch: "3"
samples:
    0: "COMBINED_TG1465133"
    1: "COMBINED_TG1466161"
    2: "COMBINED_TG1466583"
    3: "COMBINED_TG1465063"
    4: "COMBINED_TG1466525"
    5: "COMBINED_TG1466177"
    6: "COMBINED_TG1465121"
    7: "COMBINED_TG1465953"
    8: "COMBINED_TG1466359"
    9: "COMBINED_TG1466569"
