batch: "1"
samples:
    0: "TB_TG1466173_S23_L001"
    1: "TB_TG1466495_S146_L001"
    2: "TB-TG1461533_L008"
    3: "TB-TG1461639_L008"
    4: "TB-TG1467479_L008"
    5: "TB_TG1466433_S119_L001"
    6: "TB_TG1466395_S101_L001"
    7: "TB-TG1465023_L008"
    8: "TB-TG1461475_L008"
    9: "TB-TG1465105_L008"
