batch: "3"
samples:
    0: "COMBINED_TG1464981"
    1: "COMBINED_TG1466535"
    2: "COMBINED_TG1466589"
    3: "COMBINED_TG1466393"
    4: "COMBINED_TG1465821"
    5: "COMBINED_TG1467101"
    6: "COMBINED_TG1467073"
    7: "COMBINED_TG1465089"
    8: "COMBINED_TG1467099"
    9: "COMBINED_TG1466231"
