batch: "0"
samples:
    0: "5187_L004"
    1: "13109_L003"
    2: "18027_L003"
    3: "16921_L004"
    4: "3685_L004"
    5: "4510_L003"
    6: "2013-9026_L003"
    7: "4297_L004"
    8: "2016-10439_L004"
    9: "3567_L003"
