batch: "3"
samples:
    0: "COMBINED_TG1465005"
    1: "COMBINED_TG1466423"
    2: "COMBINED_TG1466139"
    3: "COMBINED_TG1466207"
    4: "COMBINED_TG1466683"
    5: "COMBINED_TG1466803"
    6: "COMBINED_TG1466979"
    7: "COMBINED_TG1467203"
    8: "COMBINED_TG1467211"
    9: "COMBINED_TG1467413"
