batch: "2"
samples:
    0: "TB_TG1466751_S24_L001"
    1: "TB_TG1467169_S186_L001"
    2: "TB_TG1467119_S165_L001"
    3: "TB_TG1466829_S54_L001"
    4: "TB_TG1466761_S28_L001"
    5: "TB_TG1466773_S34_L001"
    6: "TB_TG1466869_S70_L001"
    7: "TB_TG1466879_S132_L001"
    8: "TB_TG1466729_S14_L001"
    9: "TB_TG1466993_S122_L001"
