batch: "1"
samples:
    0: "TB-TG1467331_L008"
    1: "TB-TG1467515_L008"
    2: "TB-TG1465513_L008"
    3: "TB-TG1465187_L008"
    4: "TB-TG1465083_L008"
    5: "TB-TG1465547_L008"
    6: "TB_TG1466669_S215_L001"
    7: "TB-TG1465501_L008"
    8: "TB-TG1461547_L008"
    9: "TB_TG1466537_S163_L001"
