batch: "2"
samples:
    0: "TB_TG1466931_S96_L001"
    1: "TB_TG1466977_S115_L001"
    2: "TB_TG1466995_S123_L001"
    3: "TB_TG1466885_S77_L001"
    4: "TB_TG1467149_S177_L001"
    5: "TB_TG1466809_S47_L001"
    6: "TB_TG1467205_S199_L001"
    7: "TB_TG1467127_S167_L001"
    8: "TB_TG1467145_S175_L001"
    9: "TB_TG1467187_S194_L001"
