batch: "1"
samples:
    0: "TB-TG1465781_L008"
    1: "TB_TG1466519_S155_L001"
    2: "TB-TG1461501_L008"
    3: "TB-TG1461693_L008"
    4: "TB_TG1466353_S85_L001"
    5: "TB_TG1466369_S92_L001"
    6: "TB-TG1461707_L008"
    7: "TB_TG1466273_S57_L001"
    8: "TB_TG1466605_S188_L001"
    9: "TB-TG1465599_L008"
