batch: "1"
samples:
    0: "TB-TG1465135_L008"
    1: "TB-TG1461459_L008"
    2: "TB-TG1466081_L008"
    3: "TB_TG1466655_S209_L001"
    4: "TB-TG1465479_L008"
    5: "TB-TG1465089_L008"
    6: "TB-TG1461635_L008"
    7: "TB_TG1466309_S68_L001"
    8: "TB-TG1461719_L008"
    9: "TB-TG1465097_L008"
