batch: "1"
samples:
    0: "TB_TG1466587_S181_L001"
    1: "TB-TG1467307_L008"
    2: "TB-TG1461575_L008"
    3: "TB-TG1461755_L008"
    4: "TB_TG1466295_S62_L001"
    5: "TB-TG1465993_L008"
    6: "TB-TG1461593_L008"
    7: "TB-TG1461491_L008"
    8: "TB-TG1465877_L008"
    9: "TB_TG1466235_S43_L001"
