batch: "1"
samples:
    0: "TB-TG1465845_L008"
    1: "TB-TG1465899_L008"
    2: "TB-TG1466051_L008"
    3: "TB-TG1465139_L008"
    4: "TB_TG1466157_S18_L001"
    5: "TB-TG1466007_L008"
    6: "TB_TG1466509_S150_L001"
    7: "TB-TG1466025_L008"
    8: "TB-TG1467459_L008"
    9: "TB_TG1466249_S47_L001"
