batch: "1"
samples:
    0: "TB-TG1466017_L008"
    1: "TB-TG1464971_L008"
    2: "TB-TG1467247_L008"
    3: "TB-TG1461677_L008"
    4: "TB_TG1466473_S138_L001"
    5: "TB_TG1466327_S77_L001"
    6: "TB-TG1465253_L008"
    7: "TB-TG1461711_L008"
    8: "TB-TG1465077_L008"
    9: "TB-TG1465107_L008"
