batch: "0"
samples:
    0: "20108_L003"
    1: "9304_L003"
    2: "2015-1204_L004"
    3: "5339_L003"
    4: "19774_L003"
    5: "2014-3205_L003"
    6: "4547_L003"
    7: "17396_L003"
    8: "6062_L003"
    9: "4809_L003"
