batch: "0"
samples:
    0: "2598_L004"
    1: "24261_L004"
    2: "25357_L004"
    3: "18782_L003"
    4: "2849_L004"
    5: "13103_L003"
    6: "13294_L003"
    7: "2472_L004"
    8: "19451_L004"
    9: "7696_L004"
