batch: "1"
samples:
    0: "TB-TG1465193_L008"
    1: "TB_TG1466611_S190_L001"
    2: "TB-TG1467303_L008"
    3: "TB-TG1465227_L008"
    4: "TB-TG1461683_L008"
    5: "TB-TG1465835_L008"
    6: "TB-TG1465861_L008"
    7: "TB_TG1466131_S10_L001"
    8: "TB-TG1467441_L008"
    9: "TB_TG1466385_S98_L001"
