batch: "3"
samples:
    0: "COMBINED_TG1465799"
    1: "COMBINED_TG1466547"
    2: "COMBINED_TG1467135"
    3: "COMBINED_TG1467087"
    4: "COMBINED_TG1466899"
    5: "COMBINED_TG1466797"
    6: "COMBINED_TG1466149"
    7: "COMBINED_TG1465039"
    8: "COMBINED_TG1466183"
    9: "COMBINED_TG1466905"
