batch: "0"
samples:
    0: "567_L004"
    1: "8508_L004"
    2: "2013-3693_L003"
    3: "1943_L004"
    4: "1144_L004"
    5: "20136_L004"
    6: "13632_L004"
    7: "13850_L003"
    8: "10021_L003"
    9: "25568_L004"
