batch: "3"
samples:
    0: "COMBINED_TG1465875"
    1: "COMBINED_TG1466777"
    2: "COMBINED_TG1466019"
    3: "COMBINED_TG1466289"
    4: "COMBINED_TG1466553"
    5: "COMBINED_TG1466497"
    6: "COMBINED_TG1465559"
    7: "COMBINED_TG1466531"
    8: "COMBINED_TG1467021"
    9: "COMBINED_TG1467419"
