batch: "3"
samples:
    0: "COMBINED_TG1466717"
    1: "COMBINED_TG1466371"
    2: "COMBINED_TG1465861"
    3: "COMBINED_TG1467363"
    4: "COMBINED_TG1467183"
    5: "COMBINED_TG1467115"
    6: "COMBINED_TG1467199"
    7: "COMBINED_TG1466503"
    8: "COMBINED_TG1464991"
    9: "COMBINED_TG1466933"
