batch: "0"
samples:
    0: "3370_L003"
    1: "12440_L003"
    2: "14419_L003"
    3: "4614_L003"
    4: "2073_L004"
    5: "20518_L003"
    6: "11267_L004"
    7: "21720_L004"
    8: "13877_L004"
    9: "1397_L003"
