batch: "0"
samples:
    0: "13402_L004"
    1: "851_L004"
    2: "2529_L003"
    3: "835_L004"
    4: "14314_L003"
    5: "1584_L004"
    6: "22057_L004"
    7: "6121_L004"
    8: "6325_L004"
    9: "10898_L004"
