batch: "1"
samples:
    0: "TB-TG1461495_L008"
    1: "TB-TG1461571_L008"
    2: "TB-TG1465485_L008"
    3: "TB-TG1467487_L008"
    4: "TB_TG1466421_S114_L001"
    5: "TB-TG1465585_L008"
    6: "TB-TG1461493_L008"
    7: "TB-TG1465235_L008"
    8: "TB-TG1467357_L008"
    9: "TB_TG1466383_S97_L001"
