batch: "0"
samples:
    0: "9981_L004"
    1: "16625_L004"
    2: "2723_L003"
    3: "12998_L004"
    4: "326_L003"
    5: "9146_L004"
    6: "4066_L003"
    7: "5635_L004"
    8: "8653_L004"
    9: "10896_L003"
