batch: "3"
samples:
    0: "COMBINED_TG1465191"
    1: "COMBINED_TG1465869"
    2: "COMBINED_TG1466197"
    3: "COMBINED_TG1466527"
    4: "COMBINED_TG1465017"
    5: "COMBINED_TG1465593"
    6: "COMBINED_TG1466025"
    7: "COMBINED_TG1466457"
    8: "COMBINED_TG1466339"
    9: "COMBINED_TG1465473"
