batch: "0"
samples:
    0: "3709_L004"
    1: "10434_L003"
    2: "202_L003"
    3: "5504_L003"
    4: "10332_L004"
    5: "10818_L004"
    6: "2137_L004"
    7: "12550_L003"
    8: "2010-18935_L003"
    9: "7135_L004"
