batch: "1"
samples:
    0: "TB-TG1461749_L008"
    1: "TB-TG1467497_L008"
    2: "TB-TG1465149_L008"
    3: "TB-TG1465075_L008"
    4: "TB_TG1466193_S30_L001"
    5: "TB-TG1467377_L008"
    6: "TB_TG1466111_S3_L001"
    7: "TB_TG1466441_S123_L001"
    8: "TB_tg1461623_S13_L001"
    9: "TB-TG1465071_L008"
