batch: "3"
samples:
    0: "COMBINED_TG1466543"
    1: "COMBINED_TG1466889"
    2: "COMBINED_TG1466285"
    3: "COMBINED_TG1467319"
    4: "COMBINED_TG1466181"
    5: "COMBINED_TG1461679"
    6: "COMBINED_TG1466861"
    7: "COMBINED_TG1464983"
    8: "COMBINED_TG1465973"
    9: "COMBINED_TG1467407"
