batch: "0"
samples:
    0: "2013-3788_L003"
    1: "7200_L004"
    2: "3920_L003"
    3: "1564_L003"
    4: "1960_L004"
    5: "8062_L003"
    6: "9062_L003"
    7: "9670_L004"
    8: "2010-16950_L003"
    9: "4008_L003"
