batch: "2"
samples:
    0: "TB_TG1466733_S16_L001"
    1: "TB_TG1467147_S176_L001"
    2: "TB_TG1467177_S189_L001"
    3: "TB_TG1467237_S214_L001"
    4: "TB_TG1466753_S25_L001"
    5: "TB_TG1467055_S146_L001"
    6: "TB_TG1466873_S72_L001"
    7: "TB_TG1466757_S141_L001"
    8: "TB_TG1466967_S110_L001"
    9: "TB_TG1467003_S127_L001"
