batch: "0"
samples:
    0: "5451_L004"
    1: "4257_L003"
    2: "20296_L003"
    3: "16287_L004"
    4: "10201_L004"
    5: "267_L004"
    6: "7461_L003"
    7: "17778_L003"
    8: "22559_L003"
    9: "9033_L003"
