batch: "1"
samples:
    0: "TB_TG1466507_S149_L001"
    1: "TB-TG1467341_L008"
    2: "TB-TG1466103_L008"
    3: "TB-TG1465117_L008"
    4: "TB-TG1465891_L008"
    5: "TB-TG1461713_L008"
    6: "TB_TG1466403_S105_L001"
    7: "TB-TG1466009_L008"
    8: "TB-TG1465997_L008"
    9: "TB_TG1466179_S25_L001"
