batch: "0"
samples:
    0: "6002_L004"
    1: "22223_L004"
    2: "6029_L003"
    3: "21284_L004"
    4: "6343_L003"
    5: "4914_L003"
    6: "2889_L004"
    7: "1380_L003"
    8: "8144_L003"
    9: "1417_L003"
