batch: "1"
samples:
    0: "TB-TG1466041_L008"
    1: "TB_TG1466211_S35_L001"
    2: "TB_TG1466361_S88_L001"
    3: "TB-TG1461489_L008"
    4: "TB_TG1466517_S154_L001"
    5: "TB_TG1466497_S147_L001"
    6: "TB-TG1461543_L008"
    7: "TB-TG1465789_L008"
    8: "TB-TG1466043_L008"
    9: "TB-TG1466053_L008"
