batch: "2"
samples:
    0: "TB_TG1466821_S51_L001"
    1: "TB_TG1467067_S149_L001"
    2: "TB_TG1466893_S80_L001"
    3: "TB_TG1467159_S182_L001"
    4: "TB_TG1466743_S140_L001"
    5: "TB_TG1466883_S76_L001"
    6: "TB_TG1466817_S145_L001"
    7: "TB_TG1467009_S130_L001"
    8: "TB_TG1466795_S42_L001"
    9: "TB_TG1466907_S85_L001"
