batch: "2"
samples:
    0: "TB_TG1467005_S128_L001"
    1: "TB_TG1466923_S92_L001"
    2: "TB_TG1467077_S151_L001"
    3: "TB_TG1466705_S134_L001"
    4: "TB_TG1466785_S37_L001"
    5: "TB_TG1466901_S82_L001"
    6: "TB_TG1467239_S215_L001"
    7: "TB_TG1466865_S148_L001"
    8: "TB_TG1466825_S146_L001"
    9: "TB_TG1467175_S188_L001"
