batch: "1"
samples:
    0: "TB-TG1465171_L008"
    1: "TB-TG1465597_L008"
    2: "TB_TG1466585_S180_L001"
    3: "TB-TG1466029_L008"
    4: "TB-TG1465007_L008"
    5: "TB-TG1465249_L008"
    6: "TB-TG1465767_L008"
    7: "TB-TG1465033_L008"
    8: "TB-TG1465031_L008"
    9: "TB-TG1465095_L008"
