batch: "1"
samples:
    0: "TB_TG1466271_S56_L001"
    1: "TB-TG1461687_L008"
    2: "TB-TG1466067_L008"
    3: "TB-TG1467339_L008"
    4: "TB_TG1466411_S109_L001"
    5: "TB_TG1466437_S121_L001"
    6: "TB_TG1466247_S46_L001"
    7: "TB-TG1464969_L008"
    8: "TB-TG1461629_L008"
    9: "TB_TG1466555_S170_L001"
