batch: "0"
samples:
    0: "20040_L003"
    1: "2854_L003"
    2: "4706_L004"
    3: "10812_L004"
    4: "11615_L003"
    5: "686_L004"
    6: "8120_L004"
    7: "16905_L003"
    8: "18041_L004"
    9: "3252_L004"
