batch: "0"
samples:
    0: "13186_L003"
    1: "12684_L003"
    2: "12318_L003"
    3: "680_L003"
    4: "17723_L003"
    5: "4679_L004"
    6: "6900_L004"
    7: "14883_L004"
    8: "16889_L003"
    9: "7132_L003"
