batch: "0"
samples:
    0: "10204_L004"
    1: "13447_L003"
    2: "17985_L003"
    3: "21804_L004"
    4: "2733_L004"
    5: "7306_L004"
    6: "210_L004"
    7: "6813_L003"
    8: "10218_L003"
    9: "16969_L003"
