batch: "0"
samples:
    0: "21602_L004"
    1: "5864_L004"
    2: "717_L004"
    3: "12301_L003"
    4: "13491_L003"
    5: "13508_L003"
    6: "14736_L003"
    7: "221_L004"
    8: "13749_L004"
    9: "5625_L004"
