batch: "0"
samples:
    0: "16751_L003"
    1: "2010-3453_L003"
    2: "5706_L004"
    3: "23002_L004"
    4: "3108_L004"
    5: "4805_L003"
    6: "9905_L004"
    7: "6708_L003"
    8: "11528_L004"
    9: "7976_L003"
