batch: "1"
samples:
    0: "TB-TG1465099_L008"
    1: "TB_TG1466115_S4_L001"
    2: "TB-TG1465779_L008"
    3: "TB_TG1466427_S116_L001"
    4: "TB_TG1466451_S128_L001"
    5: "TB-TG1461739_L008"
    6: "TB-TG1467271_L008"
    7: "TB-TG1467269_L008"
    8: "TB-TG1461661_L008"
    9: "TB-TG1465917_L008"
