batch: "1"
samples:
    0: "TB-TG1466013_L008"
    1: "TB-TG1461685_L008"
    2: "TB-TG1465283_L008"
    3: "TB-TG1465895_L008"
    4: "TB-TG1467431_L008"
    5: "TB_TG1466665_S214_L001"
    6: "TB-TG1466021_L008"
    7: "TB-TG1461709_L008"
    8: "TB-TG1465889_L008"
    9: "TB-TG1465275_L008"
