batch: "1"
samples:
    0: "TB-TG1467523_L008"
    1: "TB-TG1465807_L008"
    2: "TB-TG1467481_L008"
    3: "TB-TG1467395_L008"
    4: "TB-TG1465787_L008"
    5: "TB-TG1465053_L008"
    6: "TB-TG1467353_L008"
    7: "TB_TG1466317_S72_L001"
    8: "TB_tg1461631_S16_L001"
    9: "TB_TG1466455_S130_L001"
