batch: "0"
samples:
    0: "4267_L003"
    1: "11671_L004"
    2: "3851_L004"
    3: "2161_L004"
    4: "4458_L004"
    5: "2536_L004"
    6: "15830_L004"
    7: "2012-16950_L003"
    8: "4163_L004"
    9: "9058_L003"
