batch: "2"
samples:
    0: "TB_TG1466863_S69_L001"
    1: "TB_TG1466971_S112_L001"
    2: "TB_TG1466835_S57_L001"
    3: "TB_TG1466911_S87_L001"
    4: "TB_TG1466827_S53_L001"
    5: "TB_TG1466721_S138_L001"
    6: "TB_TG1466963_S108_L001"
    7: "TB_TG1466955_S106_L001"
    8: "TB_TG1466693_S5_L001"
    9: "TB_TG1466983_S117_L001"
