batch: "1"
samples:
    0: "TB-TG1465035_L008"
    1: "TB-TG1465549_L008"
    2: "TB-TG1465241_L008"
    3: "TB_TG1466365_S90_L001"
    4: "TB_TG1466397_S102_L001"
    5: "TB-TG1465067_L008"
    6: "TB-TG1466033_L008"
    7: "TB-TG1467519_L008"
    8: "TB-TG1467293_L008"
    9: "TB-TG1461525_L008"
