batch: "0"
samples:
    0: "62_L003"
    1: "2016-7725_L004"
    2: "3921_L003"
    3: "18571_L003"
    4: "13969_L004"
    5: "21095_L004"
    6: "4152_L004"
    7: "9816_L003"
    8: "1337_L004"
    9: "8097_L003"
