batch: "1"
samples:
    0: "TB_tg1461605_S5_L001"
    1: "TB-TG1465251_L008"
    2: "TB-TG1467273_L008"
    3: "TB-TG1466085_L008"
    4: "TB-TG1461681_L008"
    5: "TB-TG1465087_L008"
    6: "TB-TG1465113_L008"
    7: "TB_TG1466117_S5_L001"
    8: "TB-TG1467383_L008"
    9: "TB-TG1465169_L008"
