batch: "0"
samples:
    0: "3454_L003"
    1: "2446_L004"
    2: "9391_L004"
    3: "10473_L003"
    4: "11821_L004"
    5: "3466_L004"
    6: "13886_L003"
    7: "18059_L004"
    8: "5929_L004"
    9: "10381_L004"
