batch: "0"
samples:
    0: "2012-8190_L003"
    1: "12273_L003"
    2: "19267_L003"
    3: "13439_L003"
    4: "5606_L004"
    5: "5026_L004"
    6: "21006_L004"
    7: "22066_L004"
    8: "6913_L004"
    9: "21361_L004"
