batch: "0"
samples:
    0: "1994_L003"
    1: "22696_L004"
    2: "17930_L004"
    3: "4175_L003"
    4: "512_L003"
    5: "456_L004"
    6: "11068_L003"
    7: "15243_L003"
    8: "17742_L004"
    9: "2013-3141_L003"
