batch: "1"
samples:
    0: "TB_TG1466355_S86_L001"
    1: "TB-TG1464989_L008"
    2: "TB_TG1466349_S83_L001"
    3: "TB-TG1465073_L008"
    4: "TB-TG1465527_L008"
    5: "TB_TG1466417_S112_L001"
    6: "TB-TG1465851_L008"
    7: "TB-TG1461519_L008"
    8: "TB-TG1461663_L008"
    9: "TB-TG1465029_L008"
