batch: "0"
samples:
    0: "1148_L003"
    1: "2016-9026_L004"
    2: "9145_L004"
    3: "2021_L003"
    4: "339_L003"
    5: "16830_L003"
    6: "320_L003"
    7: "8558_L004"
    8: "16771_L003"
    9: "598_L004"
