batch: "3"
samples:
    0: "COMBINED_TG1467011"
    1: "COMBINED_TG1467507"
    2: "COMBINED_TG1466129"
    3: "COMBINED_TG1466005"
    4: "COMBINED_TG1466337"
    5: "COMBINED_TG1466667"
    6: "COMBINED_TG1461519"
    7: "COMBINED_TG1464995"
    8: "COMBINED_TG1464967"
    9: "COMBINED_TG1465509"
