batch: "0"
samples:
    0: "22183_L004"
    1: "7013_L003"
    2: "2748_L004"
    3: "8336_L003"
    4: "2015-336_L004"
    5: "4492_L003"
    6: "2792_L004"
    7: "6915_L003"
    8: "7692_L004"
    9: "1233_L003"
