batch: "1"
samples:
    0: "TB-TG1465815_L008"
    1: "TB-TG1467419_L008"
    2: "TB-TG1467443_L008"
    3: "TB_TG1466547_S167_L001"
    4: "TB-TG1465511_L008"
    5: "TB-TG1465829_L008"
    6: "TB-TG1461699_L008"
    7: "TB_TG1466457_S131_L001"
    8: "TB-TG1467263_L008"
    9: "TB-TG1467317_L008"
