batch: "0"
samples:
    0: "19929_L004"
    1: "14740_L003"
    2: "15052_L004"
    3: "15874_L004"
    4: "14208_L003"
    5: "2010-3061_L003"
    6: "5977_L003"
    7: "7900_L004"
    8: "9314_L004"
    9: "46_L004"
