batch: "1"
samples:
    0: "TB-TG1465463_L008"
    1: "TB-TG1467253_L008"
    2: "TB_TG1466387_S99_L001"
    3: "TB-TG1461731_L008"
    4: "TB_TG1466429_S117_L001"
    5: "TB-TG1465231_L008"
    6: "TB-TG1467301_L008"
    7: "TB_tg1461595_S1_L001"
    8: "TB-TG1465503_L008"
    9: "TB-TG1465581_L008"
