batch: "1"
samples:
    0: "TB-TG1467435_L008"
    1: "TB-TG1465953_L008"
    2: "TB_TG1466471_S137_L001"
    3: "TB-TG1465911_L008"
    4: "TB_TG1466307_S67_L001"
    5: "TB_TG1466463_S134_L001"
    6: "TB_tg1461611_S8_L001"
    7: "TB-TG1467405_L008"
    8: "TB-TG1467423_L008"
    9: "TB_TG1466447_S126_L001"
