batch: "0"
samples:
    0: "12515_L003"
    1: "15473_L004"
    2: "2044_L003"
    3: "9766_L003"
    4: "14251_L003"
    5: "6188_L004"
    6: "21205_L004"
    7: "8760_L003"
    8: "11783_L003"
    9: "10221_L003"
