batch: "1"
samples:
    0: "TB-TG1465229_L008"
    1: "TB-TG1465515_L008"
    2: "TB_TG1466297_S63_L001"
    3: "TB-TG1465491_L008"
    4: "TB-TG1465927_L008"
    5: "TB_TG1466381_S96_L001"
    6: "TB_TG1466267_S55_L001"
    7: "TB-TG1467421_L008"
    8: "TB-TG1465867_L008"
    9: "TB_TG1466561_S173_L001"
