batch: "1"
samples:
    0: "TB-TG1467299_L008"
    1: "TB-TG1465015_L008"
    2: "TB-TG1466095_L008"
    3: "TB_TG1466135_S12_L001"
    4: "TB-TG1461723_L008"
    5: "TB_TG1466641_S204_L001"
    6: "TB-TG1465925_L008"
    7: "TB-TG1465973_L008"
    8: "TB_TG1466311_S69_L001"
    9: "TB-TG1465039_L008"
