batch: "1"
samples:
    0: "TB-TG1465103_L008"
    1: "TB_TG1466145_S15_L001"
    2: "TB-TG1465537_L008"
    3: "TB-TG1465923_L008"
    4: "TB-TG1465955_L008"
    5: "TB-TG1467401_L008"
    6: "TB_TG1466217_S38_L001"
    7: "TB-TG1467485_L008"
    8: "TB-TG1461729_L008"
    9: "TB-TG1464975_L008"
