batch: "0"
samples:
    0: "1820_L003"
    1: "19319_L003"
    2: "5798_L003"
    3: "6810_L003"
    4: "10543_L003"
    5: "8067_L003"
    6: "4660_L004"
    7: "2897_L004"
    8: "8261_L004"
    9: "1327_rerun_S203_L001"
