batch: "0"
samples:
    0: "10758_L004"
    1: "16379_L003"
    2: "2741_L004"
    3: "11935_L003"
    4: "850_L003"
    5: "2725_L003"
    6: "5773_L003"
    7: "13510_L003"
    8: "16488_L004"
    9: "25528_L004"
