batch: "1"
samples:
    0: "TB-TG1461727_L008"
    1: "TB-TG1467449_L008"
    2: "TB-TG1465447_L008"
    3: "TB_TG1466593_S183_L001"
    4: "TB-TG1465785_L008"
    5: "TB_TG1466215_S37_L001"
    6: "TB-TG1465567_L008"
    7: "TB-TG1461461_L008"
    8: "TB_TG1466125_S8_L001"
    9: "TB_TG1466299_S64_L001"
