batch: "0"
samples:
    0: "4948_L003"
    1: "4891_L003"
    2: "2342_L004"
    3: "4397_L004"
    4: "5439_L004"
    5: "9752_L004"
    6: "15922_L004"
    7: "14645_L003"
    8: "10950_L004"
    9: "1813_L003"
