batch: "0"
samples:
    0: "7148_L004"
    1: "2234_L003"
    2: "17125_L003"
    3: "16768_L004"
    4: "4171_L004"
    5: "369_L004"
    6: "2715_L003"
    7: "10769_L004"
    8: "1328_L004"
    9: "2016-10437_L004"
