batch: "1"
samples:
    0: "TB-TG1467373_L008"
    1: "TB-TG1461539_L008"
    2: "TB-TG1465129_L008"
    3: "TB-TG1461743_L008"
    4: "TB-TG1465265_L008"
    5: "TB_TG1466619_S194_L001"
    6: "TB-TG1461735_L008"
    7: "TB-TG1465469_L008"
    8: "TB-TG1461757_L008"
    9: "TB-TG1465177_L008"
