batch: "0"
samples:
    0: "3592_L004"
    1: "1897_L003"
    2: "19500_L003"
    3: "5037_L004"
    4: "14505_L004"
    5: "842_L004"
    6: "2010-1204_L003"
    7: "9018_L004"
    8: "19639_L004"
    9: "4281_L003"
