batch: "1"
samples:
    0: "TB_TG1466191_S29_L001"
    1: "TB-TG1467463_L008"
    2: "TB-TG1465243_L008"
    3: "TB-TG1465255_L008"
    4: "TB-TG1465131_L008"
    5: "TB-TG1467451_L008"
    6: "TB_TG1466609_S189_L001"
    7: "TB_TG1466661_S212_L001"
    8: "TB-TG1465165_L008"
    9: "TB_TG1466483_S141_L001"
