batch: "1"
samples:
    0: "TB_TG1466671_S216_L001"
    1: "TB-TG1465209_L008"
    2: "TB_TG1466261_S53_L001"
    3: "TB_TG1466335_S81_L001"
    4: "TB-TG1467295_L008"
    5: "TB_TG1466167_S21_L001"
    6: "TB-TG1461509_L008"
    7: "TB-TG1465059_L008"
    8: "TB-TG1465561_L008"
    9: "TB-TG1467365_L008"
