batch: "3"
samples:
    0: "COMBINED_TG1465885"
    1: "COMBINED_TG1466241"
    2: "COMBINED_TG1467191"
    3: "COMBINED_TG1466957"
    4: "COMBINED_TG1464985"
    5: "COMBINED_TG1467107"
    6: "COMBINED_TG1465045"
    7: "COMBINED_TG1466067"
    8: "COMBINED_TG1465123"
    9: "COMBINED_TG1466155"
