batch: "2"
samples:
    0: "TB_TG1466927_S94_L001"
    1: "TB_TG1467117_S164_L001"
    2: "TB_TG1466233_S82_L001"
    3: "TB_TG1466771_S33_L001"
    4: "TB_TG1466787_S38_L001"
    5: "TB_TG1466837_S58_L001"
    6: "TB_TG1467229_S210_L001"
    7: "TB_TG1466997_S124_L001"
    8: "TB_TG1466847_S63_L001"
    9: "TB_TG1466801_S43_L001"
