batch: "1"
samples:
    0: "TB-TG1465551_L008"
    1: "TB-TG1465037_L008"
    2: "TB-TG1464999_L008"
    3: "TB-TG1465793_L008"
    4: "TB-TG1467471_L008"
    5: "TB_TG1466415_S111_L001"
    6: "TB-TG1461453_L008"
    7: "TB-TG1465855_L008"
    8: "TB-TG1461503_L008"
    9: "TB-TG1461747_L008"
