batch: "1"
samples:
    0: "TB-TG1465133_L008"
    1: "TB-TG1465153_L008"
    2: "TB-TG1465587_L008"
    3: "TB_TG1466143_S14_L001"
    4: "TB-TG1465791_L008"
    5: "TB-TG1461579_L008"
    6: "TB-TG1465449_L008"
    7: "TB-TG1461591_L008"
    8: "TB-TG1465185_L008"
    9: "TB-TG1465021_L008"
