batch: "0"
samples:
    0: "755_L003"
    1: "8672_L003"
    2: "3689_L004"
    3: "19065_L004"
    4: "8415_L003"
    5: "10646_L004"
    6: "20030_L004"
    7: "19076_L004"
    8: "6448_L003"
    9: "2269_L003"
