batch: "0"
samples:
    0: "2013-3274_L003"
    1: "10659_L004"
    2: "7434_L003"
    3: "17843_L003"
    4: "10634_L004"
    5: "12718_L004"
    6: "8802_L003"
    7: "11148_L003"
    8: "20017_L003"
    9: "17262_L003"
