batch: "0"
samples:
    0: "7490_L003"
    1: "2783_L003"
    2: "2189_L003"
    3: "21616_L004"
    4: "8715_L003"
    5: "22248_L004"
    6: "22895_L004"
    7: "5939_L004"
    8: "4601_L003"
    9: "1628_L004"
