batch: "0"
samples:
    0: "2016-3788_L004"
    1: "11017_L003"
    2: "3039_L004"
    3: "454_L004"
    4: "642_L004"
    5: "12625_L003"
    6: "1906_L003"
    7: "11447_L004"
    8: "2193_L003"
    9: "3100_L004"
