batch: "1"
samples:
    0: "TB-TG1467489_L008"
    1: "TB-TG1465489_L008"
    2: "TB_TG1466199_S32_L001"
    3: "TB-TG1461751_L008"
    4: "TB_TG1466301_S65_L001"
    5: "TB-TG1467379_L008"
    6: "TB-TG1465233_L008"
    7: "TB-TG1467323_L008"
    8: "TB_TG1466481_S140_L001"
    9: "TB-TG1461675_L008"
