batch: "1"
samples:
    0: "TB_TG1466633_S201_L001"
    1: "TB-TG1465163_L008"
    2: "TB_TG1466107_S1_L001"
    3: "TB-TG1465451_L008"
    4: "TB-TG1465111_L008"
    5: "TB_tg1461599_S3_L001"
    6: "TB-TG1465971_L008"
    7: "TB-TG1465909_L008"
    8: "TB_TG1466313_S70_L001"
    9: "TB-TG1461647_L008"
