batch: "0"
samples:
    0: "5910_L004"
    1: "1857_L003"
    2: "21001_L003"
    3: "21311_L004"
    4: "4266_L003"
    5: "9895_L004"
    6: "18156_L003"
    7: "4362_L004"
    8: "12507_L003"
    9: "5262_L003"
