batch: "1"
samples:
    0: "TB-TG1461701_L008"
    1: "TB-TG1465055_L008"
    2: "TB-TG1465885_L008"
    3: "TB-TG1465205_L008"
    4: "TB-TG1465219_L008"
    5: "TB-TG1461705_L008"
    6: "TB-TG1461545_L008"
    7: "TB-TG1465805_L008"
    8: "TB-TG1461563_L008"
    9: "TB-TG1465543_L008"
