batch: "0"
samples:
    0: "1793_L004"
    1: "22715_L004"
    2: "23432_L004"
    3: "24769_L004"
    4: "21667_L004"
    5: "4413_L003"
    6: "15136_L003"
    7: "1703_L003"
    8: "6861_L003"
    9: "6743_L003"
