batch: "1"
samples:
    0: "TB_TG1466591_S182_L001"
    1: "TB_TG1466567_S176_L001"
    2: "TB_TG1466559_S172_L001"
    3: "TB_TG1466535_S162_L001"
    4: "TB-TG1461679_L008"
    5: "TB-TG1466093_L008"
    6: "TB-TG1461537_L008"
    7: "TB-TG1465881_L008"
    8: "TB_TG1466573_S177_L001"
    9: "TB-TG1467453_L008"
