batch: "0"
samples:
    0: "1136_L004"
    1: "1692_L003"
    2: "5199_L003"
    3: "4522_L004"
    4: "3008_L003"
    5: "2016-9210_L004"
    6: "15220_L003"
    7: "13624_L003"
    8: "7089_L004"
    9: "14220_L003"
