batch: "0"
samples:
    0: "15296_L003"
    1: "12233_L003"
    2: "6493_L003"
    3: "2012-9210_L003"
    4: "1706_L003"
    5: "24542_L003"
    6: "7397_L003"
    7: "7247_L003"
    8: "21031_L003"
    9: "5443_L003"
