batch: "0"
samples:
    0: "2505_L004"
    1: "6260_L004"
    2: "5978_L004"
    3: "15013_L003"
    4: "4835_L003"
    5: "5361_L004"
    6: "8540_L004"
    7: "316_L003"
    8: "11271_L004"
    9: "388_L004"
