batch: "1"
samples:
    0: "TB_TG1466531_S160_L001"
    1: "TB_TG1466219_S39_L001"
    2: "TB-TG1467509_L008"
    3: "TB-TG1461523_L008"
    4: "TB-TG1465195_L008"
    5: "TB-TG1465769_L008"
    6: "TB-TG1465991_L008"
    7: "TB_TG1466653_S208_L001"
    8: "TB-TG1461535_L008"
    9: "TB_TG1466377_S94_L001"
