batch: "1"
samples:
    0: "TB_TG1466351_S84_L001"
    1: "TB-TG1461759_L008"
    2: "TB-TG1465525_L008"
    3: "TB-TG1461487_L008"
    4: "TB-TG1465119_L008"
    5: "TB-TG1465533_L008"
    6: "TB-TG1467309_L008"
    7: "TB-TG1465603_L008"
    8: "TB-TG1467291_L008"
    9: "TB-TG1465825_L008"
