batch: "1"
samples:
    0: "TB_TG1466401_S104_L001"
    1: "TB-TG1461601_L008"
    2: "TB-TG1467493_L008"
    3: "TB_TG1466445_S125_L001"
    4: "TB-TG1464993_L008"
    5: "TB_TG1466505_S148_L001"
    6: "TB-TG1465773_L008"
    7: "TB-TG1465471_L008"
    8: "TB-TG1467351_L008"
    9: "TB-TG1465281_L008"
