batch: "0"
samples:
    0: "10955_L004"
    1: "6530_L003"
    2: "8452_L003"
    3: "1419_L004"
    4: "21921_L004"
    5: "10989_L004"
    6: "16999_L004"
    7: "5985_L003"
    8: "4554_L003"
    9: "5338_L003"
