batch: "3"
samples:
    0: "COMBINED_TG1466877"
    1: "COMBINED_TG1466635"
    2: "COMBINED_TG1466153"
    3: "COMBINED_TG1466727"
    4: "COMBINED_TG1465887"
    5: "COMBINED_TG1466209"
    6: "COMBINED_TG1465157"
    7: "COMBINED_TG1467051"
    8: "COMBINED_TG1465119"
    9: "COMBINED_TG1465167"
