batch: "1"
samples:
    0: "TB_TG1466245_S45_L001"
    1: "TB-TG1465933_L008"
    2: "TB-TG1465565_L008"
    3: "TB-TG1467277_L008"
    4: "TB-TG1465875_L008"
    5: "TB_TG1466227_S41_L001"
    6: "TB-TG1466077_L008"
    7: "TB-TG1465019_L008"
    8: "TB-TG1467279_L008"
    9: "TB-TG1461559_L008"
