batch: "0"
samples:
    0: "2016-4922_L004"
    1: "20638_L004"
    2: "5489_L004"
    3: "6095_L004"
    4: "7910_L003"
    5: "6879_L003"
    6: "10423_L004"
    7: "17272_L003"
    8: "13690_L003"
    9: "2013-6812_L003"
