batch: "0"
samples:
    0: "2012-3205_L003"
    1: "6242_L003"
    2: "8679_L003"
    3: "19228_L003"
    4: "11120_L004"
    5: "5923_L003"
    6: "12845_L003"
    7: "1054_L004"
    8: "8355_L003"
    9: "4673_L004"
