batch: "0"
samples:
    0: "1926_L004"
    1: "3541_L003"
    2: "7584_L004"
    3: "9533_L004"
    4: "22600_L004"
    5: "229_L003"
    6: "22242_L004"
    7: "4893_L004"
    8: "10973_L003"
    9: "5350_L003"
