batch: "0"
samples:
    0: "252_L003"
    1: "5570_L004"
    2: "10969_L003"
    3: "1554_L003"
    4: "1902_L004"
    5: "2001_L003"
    6: "3539_L003"
    7: "6426_L004"
    8: "9311_L003"
    9: "5137_L004"
