batch: "2"
samples:
    0: "TB_TG1466937_S98_L001"
    1: "TB_TG1466919_S90_L001"
    2: "TB_TG1467201_S198_L001"
    3: "TB_TG1466695_S6_L001"
    4: "TB_TG1466849_S64_L001"
    5: "TB_TG1466719_S137_L001"
    6: "TB_TG1466921_S91_L001"
    7: "TB_TG1466987_S119_L001"
    8: "TB_TG1466981_S116_L001"
    9: "TB_TG1467001_S126_L001"
