batch: "1"
samples:
    0: "TB_TG1466613_S191_L001"
    1: "TB-TG1465011_L008"
    2: "TB-TG1465969_L008"
    3: "TB-TG1465987_L008"
    4: "TB-TG1461529_L008"
    5: "TB_TG1466263_S54_L001"
    6: "TB_TG1466595_S184_L001"
    7: "TB-TG1461479_L008"
    8: "TB_TG1466407_S107_L001"
    9: "TB-TG1467275_L008"
