batch: "1"
samples:
    0: "TB-TG1465045_L008"
    1: "TB-TG1467513_L008"
    2: "TB_TG1466391_S100_L001"
    3: "TB-TG1467473_L008"
    4: "TB-TG1465571_L008"
    5: "TB-TG1467287_L008"
    6: "TB-TG1465949_L008"
    7: "TB-TG1467375_L008"
    8: "TB_TG1466419_S113_L001"
    9: "TB-TG1461637_L008"
