batch: "0"
samples:
    0: "2163_L004"
    1: "6229_L003"
    2: "20248_L003"
    3: "2624_L003"
    4: "18048_L003"
    5: "7527_L004"
    6: "4535_L004"
    7: "9272_L004"
    8: "18457_L004"
    9: "2478_L003"
