batch: "1"
samples:
    0: "TB_TG1466109_S2_L001"
    1: "TB-TG1465853_L008"
    2: "TB-TG1466055_L008"
    3: "TB-TG1466073_L008"
    4: "TB-TG1461741_L008"
    5: "TB_TG1466281_S60_L001"
    6: "TB-TG1465147_L008"
    7: "TB_TG1466477_S139_L001"
    8: "TB_TG1466151_S17_L001"
    9: "TB-TG1461657_L008"
