batch: "2"
samples:
    0: "TB_TG1467171_S187_L001"
    1: "TB_TG1467167_S185_L001"
    2: "TB_TG1467081_S153_L001"
    3: "TB_TG1467225_S208_L001"
    4: "TB_TG1466769_S32_L001"
    5: "TB_TG1467053_S145_L001"
    6: "TB_TG1466571_S117_L001"
    7: "TB_TG1467241_S216_L001"
    8: "TB_TG1467113_S162_L001"
    9: "TB_TG1466891_S79_L001"
