batch: "0"
samples:
    0: "8352_L003"
    1: "6798_L003"
    2: "17342_L004"
    3: "10709_L004"
    4: "6151_L004"
    5: "7261_L003"
    6: "8511_L004"
    7: "10228_L004"
    8: "4627_L004"
    9: "19534_L004"
