batch: "0"
samples:
    0: "3374_L004"
    1: "1676_L003"
    2: "4043_L003"
    3: "20826_L003"
    4: "15050_L004"
    5: "1859_L003"
    6: "6124_L003"
    7: "10234_L003"
    8: "8404_L004"
    9: "5763_L003"
