batch: "0"
samples:
    0: "2010-11208_L003"
    1: "694_L003"
    2: "7395_L003"
    3: "21648_L004"
    4: "4424_L004"
    5: "10689_L004"
    6: "20608_L004"
    7: "3004_L004"
    8: "12804_L003"
    9: "815_L004"
