batch: "0"
samples:
    0: "12682_L003"
    1: "15593_L003"
    2: "1268_L003"
    3: "6155_L003"
    4: "6664_L004"
    5: "3653_L003"
    6: "1907_L003"
    7: "2015-3141_L004"
    8: "10115_L003"
    9: "3145_L004"
