batch: "0"
samples:
    0: "8007_L004"
    1: "8664_L003"
    2: "14060_L004"
    3: "5098_L004"
    4: "2251_L004"
    5: "4549_L003"
    6: "2081_L004"
    7: "2887_L004"
    8: "8433_L004"
    9: "5506_L003"
