batch: "1"
samples:
    0: "TB_TG1466137_S13_L001"
    1: "TB_TG1466321_S74_L001"
    2: "TB_TG1466229_S42_L001"
    3: "TB-TG1465913_L008"
    4: "TB_TG1466239_S44_L001"
    5: "TB-TG1465541_L008"
    6: "TB-TG1461643_L008"
    7: "TB-TG1465497_L008"
    8: "TB-TG1467409_L008"
    9: "TB-TG1467501_L008"
