batch: "2"
samples:
    0: "TB_TG1466917_S89_L001"
    1: "TB_TG1466859_S67_L001"
    2: "TB_TG1466159_S69_L001"
    3: "TB_TG1466871_S71_L001"
    4: "TB_TG1466715_S11_L001"
    5: "TB_TG1466775_S35_L001"
    6: "TB_TG1467041_S161_L001"
    7: "TB_TG1467231_S211_L001"
    8: "TB_TG1466909_S86_L001"
    9: "TB_TG1466759_S27_L001"
