batch: "0"
samples:
    0: "21578_L004"
    1: "21126_L004"
    2: "22496_L004"
    3: "11856_L003"
    4: "2711_L004"
    5: "6306_L004"
    6: "8338_L003"
    7: "926_L003"
    8: "2718_L003"
    9: "3641_L004"
