batch: "0"
samples:
    0: "17569_L003"
    1: "39_L004"
    2: "12348_L004"
    3: "6600_L004"
    4: "11463_L004"
    5: "9108_L003"
    6: "7945_L003"
    7: "17015_L004"
    8: "18618_L003"
    9: "6358_L003"
