batch: "1"
samples:
    0: "TB-TG1465863_L008"
    1: "TB_TG1466357_S87_L001"
    2: "TB-TG1461659_L008"
    3: "TB-TG1465979_L008"
    4: "TB-TG1467429_L008"
    5: "TB-TG1465977_L008"
    6: "TB-TG1465553_L008"
    7: "TB-TG1465837_L008"
    8: "TB-TG1465027_L008"
    9: "TB-TG1467417_L008"
