batch: "3"
samples:
    0: "COMBINED_TG1465093"
    1: "COMBINED_TG1466043"
    2: "COMBINED_TG1466051"
    3: "COMBINED_TG1466287"
    4: "COMBINED_TG1466343"
    5: "COMBINED_TG1467189"
    6: "COMBINED_TG1465061"
    7: "COMBINED_TG1467059"
    8: "COMBINED_TG1466823"
    9: "COMBINED_TG1465803"
