batch: "0"
samples:
    0: "8520_L004"
    1: "338_L003"
    2: "21771_L004"
    3: "25047_L003"
    4: "2638_L004"
    5: "2219_L003"
    6: "21782_L004"
    7: "18689_L003"
    8: "23563_L004"
    9: "7122_L003"
