batch: "0"
samples:
    0: "4428_L004"
    1: "484_L003"
    2: "9179_L003"
    3: "14242_L003"
    4: "5507_L003"
    5: "16787_L003"
    6: "6341_L004"
    7: "2872_L003"
    8: "6555_L004"
    9: "8847_L004"
