batch: "1"
samples:
    0: "TB-TG1461737_L008"
    1: "TB_TG1466305_S66_L001"
    2: "TB-TG1467355_L008"
    3: "TB-TG1465167_L008"
    4: "TB-TG1461577_L008"
    5: "TB-TG1465941_L008"
    6: "TB-TG1461463_L008"
    7: "TB-TG1466037_L008"
    8: "TB-TG1467345_L008"
    9: "TB-TG1465869_L008"
