batch: "3"
samples:
    0: "COMBINED_TG1466293"
    1: "COMBINED_TG1465001"
    2: "COMBINED_TG1467071"
    3: "COMBINED_TG1465843"
    4: "COMBINED_TG1465969"
    5: "COMBINED_TG1466711"
    6: "COMBINED_TG1467209"
    7: "COMBINED_TG1466499"
    8: "COMBINED_TG1465569"
    9: "COMBINED_TG1466223"
