batch: "0"
samples:
    0: "7207_L004"
    1: "14044_L003"
    2: "1685_L003"
    3: "17120_L003"
    4: "21152_L004"
    5: "3915_L003"
    6: "5240_L004"
    7: "6615_L003"
    8: "5341_L003"
    9: "7084_L003"
