batch: "0"
samples:
    0: "2928_L004"
    1: "23936_L004"
    2: "11061_L004"
    3: "7911_L003"
    4: "6178_L004"
    5: "617_L003"
    6: "7984_L003"
    7: "3236_L004"
    8: "6895_L003"
    9: "19599_L003"
