batch: "3"
samples:
    0: "COMBINED_TG1466225"
    1: "COMBINED_TG1466791"
    2: "COMBINED_TG1466943"
    3: "COMBINED_TG1465867"
    4: "COMBINED_TG1464999"
    5: "COMBINED_TG1465595"
    6: "COMBINED_TG1466027"
    7: "COMBINED_TG1467181"
    8: "COMBINED_TG1466141"
    9: "COMBINED_TG1467097"
