batch: "0"
samples:
    0: "2013-336_L003"
    1: "20669_L004"
    2: "3873_L003"
    3: "11630_L004"
    4: "5213_L004"
    5: "13106_L003"
    6: "4394_L003"
    7: "10135_L003"
    8: "12403_L003"
    9: "2013-5223_L004"
