batch: "0"
samples:
    0: "20025_L003"
    1: "7168_L004"
    2: "60_L003"
    3: "2012-9263_L003"
    4: "1467_L004"
    5: "14244_L003"
    6: "15323_L004"
    7: "15714_L004"
    8: "5655_L003"
    9: "1888_L004"
