batch: "0"
samples:
    0: "7360_L004"
    1: "3502_L003"
    2: "7433_L004"
    3: "7993_L004"
    4: "2506_L004"
    5: "4488_L004"
    6: "8637_L004"
    7: "8643_L003"
    8: "9490_L004"
    9: "10503_L003"
