batch: "0"
samples:
    0: "9030_L004"
    1: "12213_L004"
    2: "16032_L004"
    3: "22124_L004"
    4: "7067_L003"
    5: "5014_L004"
    6: "7249_L003"
    7: "2948_L003"
    8: "4538_L004"
    9: "5713_L003"
