batch: "1"
samples:
    0: "TB_TG1466323_S75_L001"
    1: "TB-TG1467393_L008"
    2: "TB-TG1466075_L008"
    3: "TB-TG1465517_L008"
    4: "TB-TG1467387_L008"
    5: "TB-TG1466063_L008"
    6: "TB-TG1467249_L008"
    7: "TB-TG1465123_L008"
    8: "TB-TG1467467_L008"
    9: "TB-TG1467321_L008"
