batch: "3"
samples:
    0: "COMBINED_TG1466913"
    1: "COMBINED_TG1467173"
    2: "COMBINED_TG1466647"
    3: "COMBINED_TG1464971"
    4: "COMBINED_TG1466243"
    5: "COMBINED_TG1467409"
    6: "COMBINED_TG1466577"
    7: "COMBINED_TG1466341"
    8: "COMBINED_TG1465011"
    9: "COMBINED_TG1466475"
