batch: "0"
samples:
    0: "6028_L004"
    1: "14303_L003"
    2: "1681_L003"
    3: "211_L003"
    4: "3084_L003"
    5: "4792_L004"
    6: "13918_L003"
    7: "1831_L003"
    8: "22401_L004"
    9: "8116_L003"
