batch: "0"
samples:
    0: "1382_L004"
    1: "618_L003"
    2: "12486_L004"
    3: "4277_L004"
    4: "6301_L004"
    5: "11270_L003"
    6: "854_L003"
    7: "5224_L004"
    8: "11835_L004"
    9: "10755_L004"
