batch: "0"
samples:
    0: "13713_L003"
    1: "19436_L004"
    2: "17632_L003"
    3: "19676_L003"
    4: "10544_L003"
    5: "2589_L004"
    6: "22330_L004"
    7: "14119_L003"
    8: "194_L003"
    9: "11851_L003"
