batch: "1"
samples:
    0: "TB_TG1466465_S135_L001"
    1: "TB-TG1467525_L008"
    2: "TB-TG1461649_L008"
    3: "TB-TG1464987_L008"
    4: "TB-TG1465921_L008"
    5: "TB-TG1465047_L008"
    6: "TB-TG1465999_L008"
    7: "TB-TG1461561_L008"
    8: "TB-TG1467461_L008"
    9: "TB-TG1465595_L008"
