batch: "1"
samples:
    0: "TB-TG1465799_L008"
    1: "TB-TG1465901_L008"
    2: "TB-TG1465277_L008"
    3: "TB-TG1465801_L008"
    4: "TB-TG1461725_L008"
    5: "TB_TG1466251_S48_L001"
    6: "TB-TG1465809_L008"
    7: "TB-TG1461763_L008"
    8: "TB-TG1465575_L008"
    9: "TB_TG1466523_S157_L001"
