batch: "1"
samples:
    0: "TB-TG1465001_L008"
    1: "TB-TG1467385_L008"
    2: "TB-TG1467495_L008"
    3: "TB_TG1466399_S103_L001"
    4: "TB-TG1465161_L008"
    5: "TB-TG1466069_L008"
    6: "TB-TG1465189_L008"
    7: "TB-TG1464995_L008"
    8: "TB-TG1465783_L008"
    9: "TB-TG1466031_L008"
