batch: "3"
samples:
    0: "COMBINED_TG1465177"
    1: "COMBINED_TG1466221"
    2: "COMBINED_TG1464979"
    3: "COMBINED_TG1466557"
    4: "COMBINED_TG1467093"
    5: "COMBINED_TG1466495"
    6: "COMBINED_TG1466545"
    7: "COMBINED_TG1466265"
    8: "COMBINED_TG1465071"
    9: "COMBINED_TG1467153"
