batch: "2"
samples:
    0: "TB_TG1467235_S213_L001"
    1: "TB_TG1466793_S41_L001"
    2: "TB_TG1467045_S143_L001"
    3: "TB_TG1466843_S61_L001"
    4: "TB_TG1467109_S160_L001"
    5: "TB_TG1467193_S195_L001"
    6: "TB_TG1466681_S129_L001"
    7: "TB_TG1467207_S200_L001"
    8: "TB_TG1466925_S93_L001"
    9: "TB_TG1466941_S100_L001"
