batch: "1"
samples:
    0: "TB_TG1466413_S110_L001"
    1: "TB-TG1465883_L008"
    2: "TB_TG1466123_S7_L001"
    3: "TB-TG1465211_L008"
    4: "TB-TG1465569_L008"
    5: "TB-TG1465947_L008"
    6: "TB-TG1465939_L008"
    7: "TB-TG1465269_L008"
    8: "TB-TG1465487_L008"
    9: "TB-TG1464991_L008"
