batch: "0"
samples:
    0: "14115_L003"
    1: "6079_L004"
    2: "3389_L004"
    3: "13149_L003"
    4: "2452_L004"
    5: "5460_L004"
    6: "6967_L003"
    7: "7814_L004"
    8: "546_L003"
    9: "7955_L004"
