batch: "1"
samples:
    0: "TB-TG1465221_L008"
    1: "TB_TG1466185_S26_L001"
    2: "TB_TG1466431_S118_L001"
    3: "TB_TG1466557_S171_L001"
    4: "TB-TG1461471_L008"
    5: "TB-TG1465985_L008"
    6: "TB-TG1467511_L008"
    7: "TB-TG1461467_L008"
    8: "TB-TG1461531_L008"
    9: "TB-TG1461645_L008"
