batch: "0"
samples:
    0: "554-1_L004"
    1: "13115_L003"
    2: "10746_L004"
    3: "6557_L003"
    4: "3790_L003"
    5: "779_L004"
    6: "6608_L003"
    7: "7830_L003"
    8: "2495_L003"
    9: "6115_L003"
