batch: "0"
samples:
    0: "11979_L004"
    1: "2735_L004"
    2: "2781_L004"
    3: "25466_L004"
    4: "7169_L003"
    5: "2015-8190_L004"
    6: "6639_L004"
    7: "24028_L004"
    8: "9071_L003"
    9: "1470_L004"
