batch: "1"
samples:
    0: "TB-TG1465175_L008"
    1: "TB-TG1465857_L008"
    2: "TB_TG1466651_S207_L001"
    3: "TB-TG1467521_L008"
    4: "TB-TG1461565_L008"
    5: "TB-TG1465897_L008"
    6: "TB-TG1465959_L008"
    7: "TB_tg1461615_S10_L001"
    8: "TB-TG1466089_L008"
    9: "TB-TG1465217_L008"
