batch: "0"
samples:
    0: "7161_L003"
    1: "17326_L003"
    2: "592_L003"
    3: "4861_L004"
    4: "2480_L003"
    5: "4489_L004"
    6: "7400_L004"
    7: "1591_L004"
    8: "17386_L003"
    9: "7173_L004"
