batch: "1"
samples:
    0: "TB-TG1461449_L008"
    1: "TB-TG1461633_L008"
    2: "TB_TG1466621_S195_L001"
    3: "TB-TG1465183_L008"
    4: "TB-TG1466011_L008"
    5: "TB_TG1466637_S202_L001"
    6: "TB_TG1466515_S153_L001"
    7: "TB-TG1465841_L008"
    8: "TB-TG1465179_L008"
    9: "TB-TG1465213_L008"
