batch: "1"
samples:
    0: "TB_TG1466493_S145_L001"
    1: "TB_TG1466521_S156_L001"
    2: "TB-TG1461513_L008"
    3: "TB-TG1465539_L008"
    4: "TB-TG1467261_L008"
    5: "TB-TG1465257_L008"
    6: "TB-TG1465859_L008"
    7: "TB-TG1465833_L008"
    8: "TB-TG1467425_L008"
    9: "TB_TG1466257_S51_L001"
