batch: "0"
samples:
    0: "6834_L003"
    1: "5067_L003"
    2: "927_L004"
    3: "8231_L003"
    4: "4874_L004"
    5: "7051_L004"
    6: "1288_L003"
    7: "6398_L003"
    8: "16576_L004"
    9: "18225_L004"
