batch: "2"
samples:
    0: "TB_TG1466741_S20_L001"
    1: "TB_TG1467151_S178_L001"
    2: "TB_TG1467197_S197_L001"
    3: "TB_TG1466699_S7_L001"
    4: "TB_TG1466781_S36_L001"
    5: "TB_TG1466945_S101_L001"
    6: "TB_TG1467223_S207_L001"
    7: "TB_TG1466949_S103_L001"
    8: "TB_TG1466275_S88_L001"
    9: "TB_TG1467085_S155_L001"
