batch: "1"
samples:
    0: "TB_TG1466553_S169_L001"
    1: "TB_TG1466489_S143_L001"
    2: "TB-TG1465225_L008"
    3: "TB-TG1465093_L008"
    4: "TB-TG1465961_L008"
    5: "TB-TG1461455_L008"
    6: "TB-TG1465529_L008"
    7: "TB-TG1465245_L008"
    8: "TB_TG1466575_S178_L001"
    9: "TB-TG1461499_L008"
