batch: "0"
samples:
    0: "11069_L004"
    1: "12202_L003"
    2: "3832_L004"
    3: "5334_L004"
    4: "2204_L004"
    5: "2227_L003"
    6: "10141_L004"
    7: "53_L004"
    8: "16153_L004"
    9: "15228_L003"
