batch: "1"
samples:
    0: "TB-TG1466065_L008"
    1: "TB-TG1461567_L008"
    2: "TB-TG1466019_L008"
    3: "TB-TG1465061_L008"
    4: "TB_tg1461625_S14_L001"
    5: "TB-TG1465983_L008"
    6: "TB-TG1465843_L008"
    7: "TB-TG1467457_L008"
    8: "TB-TG1467257_L008"
    9: "TB-TG1461541_L008"
