batch: "0"
samples:
    0: "17212_L003"
    1: "19996_L004"
    2: "5222_L003"
    3: "17730_L003"
    4: "2012-6812_L003"
    5: "6086_L003"
    6: "11588_L003"
    7: "4938_L004"
    8: "17170_L003"
    9: "11472_L003"
