batch: "0"
samples:
    0: "5531_L004"
    1: "16757_L004"
    2: "5239_L004"
    3: "16391_L003"
    4: "16157_L004"
    5: "1254_L003"
    6: "24268_L004"
    7: "6616_L004"
    8: "2072_L004"
    9: "11144_L004"
