batch: "0"
samples:
    0: "7196_L004"
    1: "10728_L003"
    2: "15887_L004"
    3: "5772_L004"
    4: "3301_L004"
    5: "18911_L003"
    6: "8002_L003"
    7: "3481_L004"
    8: "22138_L004"
    9: "25228_L004"
