batch: "2"
samples:
    0: "TB_TG1467037_S141_L001"
    1: "TB_TG1467019_S134_L001"
    2: "TB_TG1466713_S10_L001"
    3: "TB_TG1466709_S9_L001"
    4: "TB_TG1467027_S137_L001"
    5: "TB_TG1466707_S135_L001"
    6: "TB_TG1466841_S60_L001"
    7: "TB_TG1467221_S206_L001"
    8: "TB_TG1467125_S13_L001"
    9: "TB_TG1466677_S1_L001"
