batch: "0"
samples:
    0: "17699_L003"
    1: "1184_L003"
    2: "83_L004"
    3: "9848_L003"
    4: "9719_L003"
    5: "1198_L003"
    6: "14989_L003"
    7: "16977_L003"
    8: "10189_L004"
    9: "2014-4922_L003"
