batch: "0"
samples:
    0: "4084_L004"
    1: "7112_L004"
    2: "23185_L004"
    3: "8787_L003"
    4: "12257_L004"
    5: "21029_L003"
    6: "9173_L003"
    7: "13908_L004"
    8: "1975_L004"
    9: "1176_L003"
