batch: "2"
samples:
    0: "TB_TG1467217_S204_L001"
    1: "TB_TG1466779_S143_L001"
    2: "TB_TG1466687_S2_L001"
    3: "TB_TG1467017_S133_L001"
    4: "TB_TG1466973_S113_L001"
    5: "TB_TG1467013_S131_L001"
    6: "TB_TG1467121_S166_L001"
    7: "TB_TG1466947_S102_L001"
    8: "TB_TG1467141_S173_L001"
    9: "TB_TG1466965_S109_L001"
