batch: "1"
samples:
    0: "TB-TG1461671_L008"
    1: "TB-TG1466015_L008"
    2: "TB-TG1465191_L008"
    3: "TB_TG1466673_S217_L001"
    4: "TB-TG1461765_L008"
    5: "TB-TG1464997_L008"
    6: "TB-TG1465143_L008"
    7: "TB-TG1467329_L008"
    8: "TB-TG1467311_L008"
    9: "TB-TG1467347_L008"
