batch: "1"
samples:
    0: "TB_TG1466491_S144_L001"
    1: "TB_TG1466623_S196_L001"
    2: "TB-TG1465261_L008"
    3: "TB-TG1465821_L008"
    4: "TB-TG1465215_L008"
    5: "TB-TG1465943_L008"
    6: "TB-TG1465907_L008"
    7: "TB-TG1465981_L008"
    8: "TB-TG1467327_L008"
    9: "TB-TG1461745_L008"
