batch: "1"
samples:
    0: "TB-TG1461507_L008"
    1: "TB-TG1465811_L008"
    2: "TB-TG1461589_L008"
    3: "TB-TG1461695_L008"
    4: "TB-TG1467415_L008"
    5: "TB_TG1466439_S122_L001"
    6: "TB-TG1465049_L008"
    7: "TB-TG1465199_L008"
    8: "TB_TG1466485_S142_L001"
    9: "TB-TG1465009_L008"
