batch: "1"
samples:
    0: "TB-TG1467285_L008"
    1: "TB_TG1466469_S136_L001"
    2: "TB-TG1465531_L008"
    3: "TB-TG1466059_L008"
    4: "TB-TG1461573_L008"
    5: "TB-TG1465507_L008"
    6: "TB-TG1465065_L008"
    7: "TB-TG1465873_L008"
    8: "TB-TG1461457_L008"
    9: "TB-TG1461667_L008"
