batch: "1"
samples:
    0: "TB_tg1461609_S7_L001"
    1: "TB-TG1461515_L008"
    2: "TB-TG1465509_L008"
    3: "TB-TG1467503_L008"
    4: "TB_TG1466435_S120_L001"
    5: "TB-TG1466049_L008"
    6: "TB-TG1461483_L008"
    7: "TB-TG1465091_L008"
    8: "TB-TG1467305_L008"
    9: "TB-TG1467315_L008"
