batch: "0"
samples:
    0: "24265_L004"
    1: "396_L004"
    2: "434_L003"
    3: "4593_L004"
    4: "5509_L003"
    5: "16207_L004"
    6: "6089_L004"
    7: "6952_L004"
    8: "7428_L003"
    9: "21797_L004"
