batch: "0"
samples:
    0: "2013-7398_L003"
    1: "235_L003"
    2: "3465_L003"
    3: "6263_L004"
    4: "1448_L003"
    5: "4774_L003"
    6: "8194_L004"
    7: "8304_L004"
    8: "1702_L003"
    9: "8965_L003"
