batch: "0"
samples:
    0: "1804_L004"
    1: "2012-4920_L003"
    2: "5914_L004"
    3: "10507_L003"
    4: "14569_L004"
    5: "5991_L003"
    6: "6227_L003"
    7: "16711_L003"
    8: "2013-2860_L003"
    9: "895_L003"
