batch: "0"
samples:
    0: "6487_L003"
    1: "2162_L004"
    2: "2013-10439_L003"
    3: "14488_L003"
    4: "5143_L003"
    5: "21919_L004"
    6: "10911_L004"
    7: "23061_L004"
    8: "7021_L003"
    9: "13790_L004"
