batch: "0"
samples:
    0: "10998_L004"
    1: "4544_L004"
    2: "10407_L004"
    3: "12430_L003"
    4: "2011-615_L003"
    5: "13188_L004"
    6: "2014-3693_L003"
    7: "12429_L003"
    8: "15684_L003"
    9: "16978_L003"
