batch: "1"
samples:
    0: "TB-TG1461761_L008"
    1: "TB-TG1465003_L008"
    2: "TB-TG1467289_L008"
    3: "TB_TG1466625_S197_L001"
    4: "TB-TG1465557_L008"
    5: "TB-TG1461527_L008"
    6: "TB-TG1465247_L008"
    7: "TB-TG1466027_L008"
    8: "TB_TG1466319_S73_L001"
    9: "TB_TG1466449_S127_L001"
