batch: "0"
samples:
    0: "15459_L004"
    1: "55_L003"
    2: "21934_L004"
    3: "13808_L004"
    4: "16482_L004"
    5: "4954_L003"
    6: "5216_L003"
    7: "7497_L003"
    8: "17986_L003"
    9: "2497_L003"
