batch: "0"
samples:
    0: "6165_L004"
    1: "9367_L003"
    2: "3449_L004"
    3: "9384_L004"
    4: "8131_L003"
    5: "2777_L003"
    6: "4736_L003"
    7: "18969_L003"
    8: "2016-5223_L004"
    9: "5885_L003"
