batch: "0"
samples:
    0: "15441_L004"
    1: "16723_L004"
    2: "4308_L004"
    3: "5611_L004"
    4: "17079_L003"
    5: "2753_L004"
    6: "2013-4920_L003"
    7: "481_L003"
    8: "1043_L003"
    9: "24188_L004"
