batch: "1"
samples:
    0: "TB-TG1465025_L008"
    1: "TB-TG1465499_L008"
    2: "TB_TG1466147_S16_L001"
    3: "TB-TG1467483_L008"
    4: "TB-TG1464977_L008"
    5: "TB-TG1466023_L008"
    6: "TB_TG1466603_S187_L001"
    7: "TB_TG1466659_S211_L001"
    8: "TB-TG1465475_L008"
    9: "TB-TG1466101_L008"
