batch: "1"
samples:
    0: "TB-TG1465931_L008"
    1: "TB-TG1465975_L008"
    2: "TB-TG1467325_L008"
    3: "TB-TG1461669_L008"
    4: "TB-TG1465267_L008"
    5: "TB-TG1461497_L008"
    6: "TB-TG1465085_L008"
    7: "TB_TG1466425_S115_L001"
    8: "TB-TG1465797_L008"
    9: "TB-TG1461673_L008"
