batch: "2"
samples:
    0: "TB_TG1466703_S133_L001"
    1: "TB_TG1466747_S22_L001"
    2: "TB_TG1466763_S29_L001"
    3: "TB_TG1466831_S55_L001"
    4: "TB_TG1466783_S144_L001"
    5: "TB_TG1466689_S3_L001"
    6: "TB_TG1466929_S95_L001"
    7: "TB_TG1466737_S18_L001"
    8: "TB_TG1466739_S19_L001"
    9: "TB_TG1467025_S136_L001"
