batch: "0"
samples:
    0: "3275_L004"
    1: "4341_L003"
    2: "7751_L003"
    3: "4289_L004"
    4: "19476_L004"
    5: "228_L003"
    6: "7835_L004"
    7: "10144_L003"
    8: "10160_L004"
    9: "12873_L003"
