batch: "0"
samples:
    0: "24080_L004"
    1: "2413_L003"
    2: "2297_L003"
    3: "2013-9263_L003"
    4: "8363_L003"
    5: "20865_L004"
    6: "1296_L004"
    7: "6567_L004"
    8: "8860_L004"
    9: "2016-615_L004"
