batch: "1"
samples:
    0: "TB-TG1465273_L008"
    1: "TB-TG1466039_L008"
    2: "TB_TG1466631_S200_L001"
    3: "TB-TG1461717_L008"
    4: "TB-TG1465495_L008"
    5: "TB_TG1466363_S89_L001"
    6: "TB-TG1467505_L008"
    7: "TB-TG1461517_L008"
    8: "TB_TG1466213_S36_L001"
    9: "TB_TG1466599_S186_L001"
