batch: "3"
samples:
    0: "COMBINED_TG1467163"
    1: "COMBINED_TG1467233"
    2: "COMBINED_TG1466345"
    3: "COMBINED_TG1465811"
    4: "COMBINED_TG1465531"
    5: "COMBINED_TG1467435"
    6: "COMBINED_TG1465091"
    7: "COMBINED_TG1465999"
    8: "COMBINED_TG1466723"
    9: "COMBINED_TG1467137"
