batch: "1"
samples:
    0: "TB-TG1461505_L008"
    1: "TB-TG1466097_L008"
    2: "TB-TG1465965_L008"
    3: "TB-TG1465915_L008"
    4: "TB_TG1466525_S158_L001"
    5: "TB-TG1467445_L008"
    6: "TB_TG1466541_S165_L001"
    7: "TB-TG1465461_L008"
    8: "TB-TG1465817_L008"
    9: "TB-TG1465473_L008"
