batch: "0"
samples:
    0: "9710_L004"
    1: "9458_L004"
    2: "11586_L004"
    3: "2012-10437_L003"
    4: "24352_L004"
    5: "8662_L003"
    6: "5085_L004"
    7: "2012-14541_L003"
    8: "8267_L003"
    9: "1205_L004"
