batch: "3"
samples:
    0: "COMBINED_TG1467495"
    1: "COMBINED_TG1464973"
    2: "COMBINED_TG1465913"
    3: "COMBINED_TG1465971"
    4: "COMBINED_TG1467519"
    5: "COMBINED_TG1467089"
    6: "COMBINED_TG1467313"
    7: "COMBINED_TG1465159"
    8: "COMBINED_TG1465801"
    9: "COMBINED_TG1466047"
