batch: "1"
samples:
    0: "TB-TG1466045_L008"
    1: "TB-TG1465483_L008"
    2: "TB-TG1465919_L008"
    3: "TB_TG1466195_S31_L001"
    4: "TB-TG1465127_L008"
    5: "TB-TG1467507_L008"
    6: "TB-TG1465151_L008"
    7: "TB-TG1465201_L008"
    8: "TB-TG1465827_L008"
    9: "TB-TG1467343_L008"
