batch: "1"
samples:
    0: "TB-TG1467349_L008"
    1: "TB_TG1466409_S108_L001"
    2: "TB-TG1467465_L008"
    3: "TB-TG1461469_L008"
    4: "TB-TG1465173_L008"
    5: "TB-TG1465937_L008"
    6: "TB-TG1465279_L008"
    7: "TB_TG1466379_S95_L001"
    8: "TB_TG1466615_S192_L001"
    9: "TB-TG1461733_L008"
