batch: "3"
samples:
    0: "COMBINED_TG1466529"
    1: "COMBINED_TG1467047"
    2: "COMBINED_TG1467301"
    3: "COMBINED_TG1467335"
    4: "COMBINED_TG1465125"
    5: "COMBINED_TG1467245"
    6: "COMBINED_TG1465477"
    7: "COMBINED_TG1465847"
    8: "COMBINED_TG1464993"
    9: "COMBINED_TG1466387"
