batch: "3"
samples:
    0: "COMBINED_TG1466467"
    1: "COMBINED_TG1466479"
    2: "COMBINED_TG1467133"
    3: "COMBINED_TG1466581"
    4: "COMBINED_TG1466645"
    5: "COMBINED_TG1466487"
    6: "COMBINED_TG1465539"
    7: "COMBINED_TG1465965"
    8: "COMBINED_TG1466113"
    9: "COMBINED_TG1467179"
