batch: "0"
samples:
    0: "3271_L004"
    1: "10445_L004"
    2: "337_L003"
    3: "14252_L004"
    4: "4366_L003"
    5: "4728_L004"
    6: "7357_L004"
    7: "5086_L004"
    8: "19579_L003"
    9: "2015-3274_L004"
