batch: "1"
samples:
    0: "TB-TG1467381_L008"
    1: "TB_TG1466277_S58_L001"
    2: "TB-TG1466005_L008"
    3: "TB-TG1467297_L008"
    4: "TB-TG1467371_L008"
    5: "TB_tg1461597_S2_L001"
    6: "TB-TG1461653_L008"
    7: "TB-TG1465041_L008"
    8: "TB-TG1467335_L008"
    9: "TB-TG1461473_L008"
