batch: "0"
samples:
    0: "4980_L003"
    1: "10157_L004"
    2: "6212_L003"
    3: "226_L003"
    4: "5623_L004"
    5: "1627_L004"
    6: "2784_L004"
    7: "13529_L004"
    8: "23045_L004"
    9: "16935_L004"
