batch: "0"
samples:
    0: "2348_L003"
    1: "4009_L004"
    2: "5825_L004"
    3: "13283_L004"
    4: "2014-18935_L003"
    5: "9335_L004"
    6: "14326_L004"
    7: "25167_L004"
    8: "1579_L003"
    9: "9942_L004"
