batch: "0"
samples:
    0: "23470_L004"
    1: "10424_L003"
    2: "3126_L003"
    3: "16817_L004"
    4: "19602_L003"
    5: "14673_L004"
    6: "1954_L003"
    7: "8089_L004"
    8: "8483_L003"
    9: "12389_L003"
