batch: "0"
samples:
    0: "6914_L004"
    1: "4918_L004"
    2: "13839_L004"
    3: "18934_L004"
    4: "18967_L004"
    5: "7321_L003"
    6: "3024_L003"
    7: "3659_L003"
    8: "2015-1266_L004"
    9: "2301_L003"
