batch: "0"
samples:
    0: "22907_L004"
    1: "9569_L003"
    2: "16009_L003"
    3: "4747_L003"
    4: "6070_L004"
    5: "1749_L003"
    6: "21365_L004"
    7: "8407_L003"
    8: "876_L004"
    9: "710_L003"
