batch: "2"
samples:
    0: "TB_TG1467139_S172_L001"
    1: "TB_TG1466701_S8_L001"
    2: "TB_TG1467083_S154_L001"
    3: "TB_TG1466203_S76_L001"
    4: "TB_TG1466807_S46_L001"
    5: "TB_TG1466789_S39_L001"
    6: "TB_TG1466903_S83_L001"
    7: "TB_TG1466691_S4_L001"
    8: "TB_TG1467161_S183_L001"
    9: "TB_TG1467043_S142_L001"
