batch: "2"
samples:
    0: "TB_TG1467215_S203_L001"
    1: "TB_TG1467057_S147_L001"
    2: "TB_TG1466725_S13_L001"
    3: "TB_TG1466735_S17_L001"
    4: "TB_TG1466811_S48_L001"
    5: "TB_TG1467039_S160_L001"
    6: "TB_TG1466915_S88_L001"
    7: "TB_TG1467023_S135_L001"
    8: "TB_TG1467079_S152_L001"
    9: "TB_TG1467195_S196_L001"
