batch: "2"
samples:
    0: "TB_TG1467243_S217_L001"
    1: "TB_TG1466985_S118_L001"
    2: "TB_TG1467015_S132_L001"
    3: "TB_TG1467007_S129_L001"
    4: "TB_TG1467029_S138_L001"
    5: "TB_TG1466951_S104_L001"
    6: "TB_TG1467049_S144_L001"
    7: "TB_TG1467129_S168_L001"
    8: "TB_TG1467165_S184_L001"
    9: "TB_TG1466745_S21_L001"
