batch: "1"
samples:
    0: "TB-TG1465285_L008"
    1: "TB-TG1465563_L008"
    2: "TB-TG1465481_L008"
    3: "TB-TG1465545_L008"
    4: "TB-TG1465593_L008"
    5: "TB_TG1466545_S166_L001"
    6: "TB-TG1461619_L008"
    7: "TB_TG1466165_S20_L001"
    8: "TB-TG1467499_L008"
    9: "TB_TG1466639_S203_L001"
