batch: "0"
samples:
    0: "4303_L004"
    1: "5295_L003"
    2: "4968_L004"
    3: "2888_L003"
    4: "14867_L004"
    5: "4582_L004"
    6: "7800_L003"
    7: "9831_L004"
    8: "16582_L003"
    9: "3448_L003"
