batch: "3"
samples:
    0: "COMBINED_TG1467111"
    1: "COMBINED_TG1466895"
    2: "COMBINED_TG1467185"
    3: "COMBINED_TG1467033"
    4: "COMBINED_TG1465603"
    5: "COMBINED_TG1464989"
    6: "COMBINED_TG1466799"
    7: "COMBINED_TG1465153"
    8: "COMBINED_TG1465025"
    9: "COMBINED_TG1466675"
