batch: "0"
samples:
    0: "20612_L003"
    1: "2937_L003"
    2: "5832_L004"
    3: "10036_L003"
    4: "10420_L004"
    5: "18771_L004"
    6: "3974_L004"
    7: "4830_L004"
    8: "3208_L004"
    9: "7379_L004"
