batch: "1"
samples:
    0: "TB-TG1465775_L008"
    1: "TB-TG1461651_L008"
    2: "TB-TG1465839_L008"
    3: "TB-TG1467517_L008"
    4: "TB-TG1465259_L008"
    5: "TB_TG1466279_S59_L001"
    6: "TB-TG1467403_L008"
    7: "TB-TG1465459_L008"
    8: "TB_TG1466169_S22_L001"
    9: "TB_tg1461621_S12_L001"
