batch: "0"
samples:
    0: "2757_L004"
    1: "13604_L003"
    2: "2014-3453_L003"
    3: "3105_L003"
    4: "3204_L003"
    5: "4429_L004"
    6: "6760_L004"
    7: "7660_L003"
    8: "12640_L003"
    9: "1779_L003"
