batch: "0"
samples:
    0: "12941_L003"
    1: "796_L003"
    2: "14373_L003"
    3: "3347_L004"
    4: "3771_L003"
    5: "265_L004"
    6: "2016-1266_L004"
    7: "8532_L003"
    8: "3850_L004"
    9: "11115_L004"
