batch: "0"
samples:
    0: "21329_L004"
    1: "21199_L004"
    2: "804_L004"
    3: "6939_L004"
    4: "14639_L004"
    5: "14701_L003"
    6: "8152_L004"
    7: "2593_L004"
    8: "19940_L004"
    9: "12580_L003"
