batch: "1"
samples:
    0: "TB-TG1467491_L008"
    1: "TB-TG1461689_L008"
    2: "TB_TG1466533_S161_L001"
    3: "TB_TG1466643_S205_L001"
    4: "TB-TG1466087_L008"
    5: "TB-TG1467439_L008"
    6: "TB_TG1466163_S19_L001"
    7: "TB_TG1466511_S151_L001"
    8: "TB-TG1465813_L008"
    9: "TB-TG1464985_L008"
