batch: "1"
samples:
    0: "TB-TG1465871_L008"
    1: "TB-TG1465457_L008"
    2: "TB-TG1465523_L008"
    3: "TB-TG1466035_L008"
    4: "TB-TG1466105_L008"
    5: "TB_tg1461627_S15_L001"
    6: "TB-TG1464981_L008"
    7: "TB-TG1465601_L008"
    8: "TB_TG1466133_S11_L001"
    9: "TB-TG1465223_L008"
