batch: "1"
samples:
    0: "TB-TG1465935_L008"
    1: "TB-TG1461581_L008"
    2: "TB-TG1465795_L008"
    3: "TB-TG1467475_L008"
    4: "TB_TG1466629_S199_L001"
    5: "TB-TG1461721_L008"
    6: "TB-TG1465197_L008"
    7: "TB_TG1466255_S50_L001"
    8: "TB_TG1466627_S198_L001"
    9: "TB-TG1465005_L008"
