batch: "0"
samples:
    0: "9296_L004"
    1: "2590_L004"
    2: "21447_L004"
    3: "6352_L003"
    4: "22534_L004"
    5: "1081_L003"
    6: "20457_L004"
    7: "19966_L004"
    8: "5565_L004"
    9: "13305_L004"
