batch: "1"
samples:
    0: "TB-TG1467399_L008"
    1: "TB_TG1466259_S52_L001"
    2: "TB_tg1461603_S4_L001"
    3: "TB-TG1466071_L008"
    4: "TB-TG1466047_L008"
    5: "TB_TG1466375_S93_L001"
    6: "TB-TG1466001_L008"
    7: "TB-TG1461697_L008"
    8: "TB-TG1465181_L008"
    9: "TB-TG1465237_L008"
