batch: "2"
samples:
    0: "TB_TG1467103_S159_L001"
    1: "TB_TG1466767_S31_L001"
    2: "TB_TG1466697_S132_L001"
    3: "TB_TG1467143_S174_L001"
    4: "TB_TG1466819_S50_L001"
    5: "TB_TG1466833_S56_L001"
    6: "TB_TG1466685_S131_L001"
    7: "TB_TG1467219_S205_L001"
    8: "TB_TG1466813_S49_L001"
    9: "TB_TG1466969_S111_L001"
