batch: "1"
samples:
    0: "TB-TG1467251_L008"
    1: "TB-TG1467281_L008"
    2: "TB_TG1466579_S179_L001"
    3: "TB-TG1465579_L008"
    4: "TB-TG1467389_L008"
    5: "TB-TG1467267_L008"
    6: "TB-TG1467397_L008"
    7: "TB-TG1467433_L008"
    8: "TB-TG1467469_L008"
    9: "TB-TG1464983_L008"
