batch: "0"
samples:
    0: "2011-14541_L003"
    1: "20148_L003"
    2: "3123_L003"
    3: "5768_L004"
    4: "11954_L003"
    5: "6471_L004"
    6: "11374_L004"
    7: "1303_L004"
    8: "24031_L004"
    9: "5458_L003"
