batch: "2"
samples:
    0: "TB_TG1466845_S62_L001"
    1: "TB_TG1466607_S123_L001"
    2: "TB_TG1466749_S23_L001"
    3: "TB_TG1466851_S65_L001"
    4: "TB_TG1466959_S107_L001"
    5: "TB_TG1466999_S125_L001"
    6: "TB_TG1467157_S181_L001"
    7: "TB_TG1466939_S99_L001"
    8: "TB_TG1467095_S10_L001"
    9: "TB_TG1466857_S66_L001"
