batch: "0"
samples:
    0: "21332_L004"
    1: "1925_L004"
    2: "16255_L003"
    3: "7217_L003"
    4: "19779_L003"
    5: "962_L004"
    6: "4210_L003"
    7: "5804_L003"
    8: "18353_L003"
    9: "2012-7725_L003"
