batch: "2"
samples:
    0: "TB_TG1467061_S148_L001"
    1: "TB_TG1467035_S140_L001"
    2: "TB_TG1466975_S114_L001"
    3: "TB_TG1467131_S169_L001"
    4: "TB_TG1466765_S30_L001"
    5: "TB_TG1466731_S15_L001"
    6: "TB_TG1466991_S121_L001"
    7: "TB_TG1466953_S105_L001"
    8: "TB_TG1466237_S83_L001"
    9: "TB_TG1466989_S120_L001"
