batch: "0"
samples:
    0: "16283_L004"
    1: "7912_L003"
    2: "266_L004"
    3: "9820_L004"
    4: "10693_L004"
    5: "4972_L003"
    6: "8011_L003"
    7: "9809_L004"
    8: "4217_L004"
    9: "11099_L004"
