batch: "1"
samples:
    0: "TB_TG1466325_S76_L001"
    1: "TB-TG1467265_L008"
    2: "TB_TG1466283_S61_L001"
    3: "TB_TG1466657_S210_L001"
    4: "TB_TG1466329_S78_L001"
    5: "TB-TG1461703_L008"
    6: "TB-TG1465453_L008"
    7: "TB_TG1466663_S213_L001"
    8: "TB-TG1461641_L008"
    9: "TB-TG1465157_L008"
