batch: "0"
samples:
    0: "9730_L003"
    1: "2775_L003"
    2: "7833_L003"
    3: "9261_L003"
    4: "1910_L004"
    5: "5937_L003"
    6: "4369_L004"
    7: "5537_L004"
    8: "21950_L004"
    9: "49_L004"
