batch: "1"
samples:
    0: "TB-TG1461553_L008"
    1: "TB-TG1465207_L008"
    2: "TB-TG1467477_L008"
    3: "TB-TG1465521_L008"
    4: "TB-TG1466099_L008"
    5: "TB_TG1466513_S152_L001"
    6: "TB_TG1466527_S159_L001"
    7: "TB_tg1461613_S9_L001"
    8: "TB-TG1465455_L008"
    9: "TB-TG1465051_L008"
