batch: "0"
samples:
    0: "21066_L004"
    1: "14032_L003"
    2: "5202_L004"
    3: "13010_L003"
    4: "19655_L003"
    5: "4828_L004"
    6: "4255_L004"
    7: "7720_L004"
    8: "2410_L003"
    9: "2207_L004"
