batch: "3"
samples:
    0: "COMBINED_TG1467227"
    1: "COMBINED_TG1466003"
    2: "COMBINED_TG1466961"
    3: "COMBINED_TG1465541"
    4: "COMBINED_TG1461471"
    5: "COMBINED_TG1466855"
    6: "COMBINED_TG1465033"
    7: "COMBINED_TG1465069"
    8: "COMBINED_TG1465481"
    9: "COMBINED_TG1466303"
