batch: "3"
samples:
    0: "COMBINED_TG1466269"
    1: "COMBINED_TG1467417"
    2: "COMBINED_TG1466389"
    3: "COMBINED_TG1466165"
    4: "COMBINED_TG1464987"
    5: "COMBINED_TG1466881"
    6: "COMBINED_TG1466875"
    7: "COMBINED_TG1467411"
    8: "COMBINED_TG1467415"
    9: "COMBINED_TG1466805"
