batch: "0"
samples:
    0: "2034_L003"
    1: "3973_L004"
    2: "3791_L003"
    3: "4640_L003"
    4: "4940_L003"
    5: "6069_L003"
    6: "6581_L003"
    7: "24981_L004"
    8: "862-1_L003"
    9: "5982_L004"
