batch: "0"
samples:
    0: "12800_L004"
    1: "22084_L004"
    2: "10101_L003"
    3: "884_L003"
    4: "7256_L004"
    5: "8147_L003"
    6: "5493_L003"
    7: "19566_L003"
    8: "15166_L003"
    9: "12637_L004"
