batch: "1"
samples:
    0: "TB-TG1466061_L008"
    1: "TB_TG1466405_S106_L001"
    2: "TB-TG1465519_L008"
    3: "TB-TG1465887_L008"
    4: "TB-TG1465591_L008"
    5: "TB_TG1466331_S79_L001"
    6: "TB-TG1465905_L008"
    7: "TB-TG1467255_L008"
    8: "TB_TG1466649_S206_L001"
    9: "TB-TG1467359_L008"
