batch: "0"
samples:
    0: "5268_L003"
    1: "7727_L004"
    2: "2013-3061_L003"
    3: "3952_L004"
    4: "6622_L003"
    5: "5108_L003"
    6: "4704_L004"
    7: "21472_L003"
    8: "22264_L004"
    9: "1789_L003"
