batch: "0"
samples:
    0: "21884_L003"
    1: "11604_L003"
    2: "9050_L003"
    3: "14676_L003"
    4: "19933_L004"
    5: "4744_L003"
    6: "1327_L003"
    7: "2667_L004"
    8: "7297_L004"
    9: "24523_L004"
