batch: "2"
samples:
    0: "TB_TG1467075_S150_L001"
    1: "TB_TG1467091_S157_L001"
    2: "TB_TG1467155_S180_L001"
    3: "TB_TG1466755_S26_L001"
    4: "TB_TG1466867_S101_L001"
    5: "TB_TG1466839_S59_L001"
    6: "TB_TG1466853_S147_L001"
    7: "TB_TG1466897_S81_L001"
    8: "TB_TG1467213_S202_L001"
    9: "TB_TG1467031_S139_L001"
