batch: "3"
samples:
    0: "COMBINED_TG1466001"
    1: "COMBINED_TG1467105"
    2: "COMBINED_TG1465487"
    3: "COMBINED_TG1465863"
    4: "COMBINED_TG1466171"
    5: "COMBINED_TG1466291"
    6: "COMBINED_TG1466551"
    7: "COMBINED_TG1466815"
    8: "COMBINED_TG1466601"
    9: "COMBINED_TG1467123"
