batch: "0"
samples:
    0: "14789_L003"
    1: "15957_L004"
    2: "2014-11208_L003"
    3: "589_L003"
    4: "11257_L003"
    5: "16838_L004"
    6: "10610_L003"
    7: "4004_L003"
    8: "6808_L004"
    9: "5783_L004"
