batch: "1"
samples:
    0: "TB-TG1465141_L008"
    1: "TB_TG1466563_S174_L001"
    2: "TB-TG1465069_L008"
    3: "TB_TG1466201_S33_L001"
    4: "TB-TG1467427_L008"
    5: "TB-TG1467455_L008"
    6: "TB-TG1465583_L008"
    7: "TB-TG1465101_L008"
    8: "TB-TG1465043_L008"
    9: "TB-TG1461549_L008"
