batch: "0"
samples:
    0: "19855_L004"
    1: "7676_L004"
    2: "839_L004"
    3: "1814_L003"
    4: "7546_L003"
    5: "8855_L003"
    6: "5385_L004"
    7: "14260_L003"
    8: "13413_L004"
    9: "2016-7398_L004"
