batch: "3"
samples:
    0: "COMBINED_TG1466373"
    1: "COMBINED_TG1466523"
    2: "COMBINED_TG1467463"
    3: "COMBINED_TG1467069"
    4: "COMBINED_TG1466061"
    5: "COMBINED_TG1466501"
    6: "COMBINED_TG1467065"
    7: "COMBINED_TG1465183"
    8: "COMBINED_TG1465823"
    9: "COMBINED_TG1465841"
