batch: "0"
samples:
    0: "16421_L004"
    1: "1036_L004"
    2: "18546_L004"
    3: "8361_L003"
    4: "14253_L004"
    5: "1416_L004"
    6: "1438_L003"
    7: "7356_L003"
    8: "14771_L003"
    9: "9100_L003"
