batch: "0"
samples:
    0: "967_L004"
    1: "2265_L003"
    2: "2811_L003"
    3: "19626_L004"
    4: "7317_L003"
    5: "1719_L004"
    6: "6449_L004"
    7: "2016-5189_L004"
    8: "541_L003"
    9: "4016_L004"
