batch: "1"
samples:
    0: "TB-TG1461569_L008"
    1: "TB-TG1465995_L008"
    2: "TB-TG1465951_L008"
    3: "TB-TG1461485_L008"
    4: "TB-TG1467333_L008"
    5: "TB-TG1461521_L008"
    6: "TB-TG1467313_L008"
    7: "TB_TG1466187_S27_L001"
    8: "TB-TG1465493_L008"
    9: "TB-TG1465879_L008"
