batch: "1"
samples:
    0: "TB-TG1461665_L008"
    1: "TB_TG1466119_S6_L001"
    2: "TB-TG1461715_L008"
    3: "TB-TG1465573_L008"
    4: "TB-TG1465957_L008"
    5: "TB_TG1466597_S185_L001"
    6: "TB-TG1465125_L008"
    7: "TB-TG1467283_L008"
    8: "TB-TG1465137_L008"
    9: "TB_TG1466223_S40_L001"
