batch: "0"
samples:
    0: "2011-2860_L003"
    1: "16118_L004"
    2: "4778_L004"
    3: "9025_L004"
    4: "13506_L004"
    5: "2866_L003"
    6: "2155_L004"
    7: "608_L003"
    8: "8164_L004"
    9: "4540_L003"
