samples:
    0: "COMBINED_TG1466223"
    1: "COMBINED_TG1467363"
    2: "COMBINED_TG1465039"
    3: "COMBINED_TG1467417"
    4: "COMBINED_TG1466475"
    5: "COMBINED_TG1466051"
    6: "COMBINED_TG1466497"
    7: "COMBINED_TG1466303"
    8: "COMBINED_TG1466373"
    9: "COMBINED_TG1466487"
    10: "COMBINED_TG1466141"
    11: "COMBINED_TG1466181"
    12: "COMBINED_TG1466265"
    13: "COMBINED_TG1466635"
    14: "COMBINED_TG1466025"
    15: "COMBINED_TG1465867"
    16: "COMBINED_TG1464987"
    17: "COMBINED_TG1467409"
    18: "COMBINED_TG1466667"
    19: "COMBINED_TG1465973"
    20: "COMBINED_TG1465481"
    21: "COMBINED_TG1466027"
    22: "COMBINED_TG1466889"
    23: "COMBINED_TG1466815"
    24: "COMBINED_TG1467211"
    25: "COMBINED_TG1464989"
    26: "COMBINED_TG1465089"
    27: "COMBINED_TG1466895"
    28: "COMBINED_TG1466499"
    29: "COMBINED_TG1465153"
    30: "COMBINED_TG1465157"
    31: "COMBINED_TG1465593"
    32: "COMBINED_TG1466647"
    33: "COMBINED_TG1466675"
    34: "COMBINED_TG1465569"
    35: "COMBINED_TG1465803"
    36: "COMBINED_TG1466791"
    37: "COMBINED_TG1467011"
    38: "COMBINED_TG1466645"
    39: "COMBINED_TG1465885"
    40: "COMBINED_TG1467051"
    41: "COMBINED_TG1467069"
    42: "COMBINED_TG1467097"
    43: "COMBINED_TG1464981"
    44: "COMBINED_TG1464991"
    45: "COMBINED_TG1466881"
    46: "COMBINED_TG1467415"
    47: "COMBINED_TG1466799"
    48: "COMBINED_TG1466155"
    49: "COMBINED_TG1465847"
