samples:
    0: "COMBINED_TG1464995"
    1: "COMBINED_TG1461471"
    2: "COMBINED_TG1461679"
    3: "COMBINED_TG1466423"
    4: "COMBINED_TG1466289"
    5: "COMBINED_TG1465061"
    6: "COMBINED_TG1465999"
    7: "COMBINED_TG1466797"
    8: "COMBINED_TG1467183"
    9: "COMBINED_TG1467115"
    10: "COMBINED_TG1465071"
    11: "COMBINED_TG1466225"
    12: "COMBINED_TG1467173"
    13: "COMBINED_TG1465887"
    14: "COMBINED_TG1465969"
    15: "COMBINED_TG1465191"
    16: "COMBINED_TG1467227"
    17: "COMBINED_TG1467063"
    18: "COMBINED_TG1464967"
    19: "COMBINED_TG1466581"
    20: "COMBINED_TG1466727"
    21: "COMBINED_TG1466359"
    22: "COMBINED_TG1466535"
    23: "COMBINED_TG1467065"
    24: "COMBINED_TG1466551"
    25: "COMBINED_TG1466067"
    26: "COMBINED_TG1466387"
    27: "COMBINED_TG1466529"
    28: "COMBINED_TG1467105"
    29: "COMBINED_TG1465861"
    30: "COMBINED_TG1466589"
    31: "COMBINED_TG1466269"
    32: "COMBINED_TG1466171"
    33: "COMBINED_TG1466113"
    34: "COMBINED_TG1467507"
    35: "COMBINED_TG1466467"
    36: "COMBINED_TG1467209"
    37: "COMBINED_TG1466209"
    38: "COMBINED_TG1466221"
    39: "COMBINED_TG1467033"
    40: "COMBINED_TG1467123"
    41: "COMBINED_TG1465011"
    42: "COMBINED_TG1465167"
    43: "COMBINED_TG1461519"
    44: "COMBINED_TG1465045"
    45: "COMBINED_TG1465093"
    46: "COMBINED_TG1466241"
    47: "COMBINED_TG1465863"
    48: "COMBINED_TG1467181"
    49: "COMBINED_TG1466153"
