samples:
    0: "COMBINED_TG1466557"
    1: "COMBINED_TG1466005"
    2: "COMBINED_TG1466345"
    3: "COMBINED_TG1466183"
    4: "COMBINED_TG1466723"
    5: "COMBINED_TG1466913"
    6: "COMBINED_TG1466003"
    7: "COMBINED_TG1467135"
    8: "COMBINED_TG1466293"
    9: "COMBINED_TG1467153"
    10: "COMBINED_TG1465001"
    11: "COMBINED_TG1467071"
    12: "COMBINED_TG1467179"
    13: "COMBINED_TG1467191"
    14: "COMBINED_TG1465799"
    15: "COMBINED_TG1467233"
    16: "COMBINED_TG1467099"
    17: "COMBINED_TG1465841"
    18: "COMBINED_TG1466527"
    19: "COMBINED_TG1464979"
    20: "COMBINED_TG1466523"
    21: "COMBINED_TG1467163"
    22: "COMBINED_TG1465487"
    23: "COMBINED_TG1466495"
    24: "COMBINED_TG1465869"
    25: "COMBINED_TG1467185"
    26: "COMBINED_TG1467101"
    27: "COMBINED_TG1466371"
    28: "COMBINED_TG1467335"
    29: "COMBINED_TG1465121"
    30: "COMBINED_TG1466503"
    31: "COMBINED_TG1466285"
    32: "COMBINED_TG1465091"
    33: "COMBINED_TG1464985"
    34: "COMBINED_TG1464973"
    35: "COMBINED_TG1465843"
    36: "COMBINED_TG1467407"
    37: "COMBINED_TG1466393"
    38: "COMBINED_TG1464999"
    39: "COMBINED_TG1466001"
    40: "COMBINED_TG1466683"
    41: "COMBINED_TG1466047"
    42: "COMBINED_TG1466343"
    43: "COMBINED_TG1466547"
    44: "COMBINED_TG1465953"
    45: "COMBINED_TG1465541"
    46: "COMBINED_TG1465965"
    47: "COMBINED_TG1466061"
    48: "COMBINED_TG1465509"
    49: "COMBINED_TG1466339"
